import {readResourceText} from './sites/resources.mjs';
import {runObservedCommand} from '../integrations/src/index.mjs';
import {parseRange,inRange} from './document-source.mjs';
import {prompt,criteriaSchemas,systemInstruction} from './pipeline-prompts.mjs';
export class CriteriaSandboxError extends Error {constructor(code,message){super(message);this.name='CriteriaSandboxError';this.code=`CRITERIA_SANDBOX_${code}`;}}
const compact=v=>String(v??'').normalize('NFKC').replace(/\s+/g,'').toLowerCase();
const unique=values=>[...new Map(values.map(v=>[JSON.stringify(v),v])).values()];
export function selectCriteriaRanges(requests,inventory,{usedArea=0,seen=new Set(),repeat=false}={}){const ranges=[],remainingRanges=[],rejected=[];let area=usedArea;for(const request of unique(requests)){const range=parseRange(request?.range),sheet=inventory.sheets.find(s=>s.name===request?.sheet);if(!sheet||!range||range.area>12000){rejected.push(request);continue;}const value={sheet:sheet.name,range:range.range},key=JSON.stringify(value);if(!repeat&&seen.has(key))continue;if(ranges.length>=18||area+range.area>24000){remainingRanges.push(value);continue;}ranges.push(value);area+=range.area;}return {ranges,remainingRanges,rejected,usedArea:area};}
export function upsertCriteriaProposals(proposals,incoming,invalidIndices=new Set()){for(const proposal of incoming){const anchors=p=>(p.citations||[]).map(e=>`${e.sheet}!${e.cell}`).sort().join('|');const replaced=proposal.replacesIndex;if(Number.isInteger(replaced)&&replaced>=0&&replaced<proposals.length&&(anchors(proposals[replaced])===anchors(proposal)||invalidIndices.has(replaced)&&compact(proposals[replaced].label)===compact(proposal.label))){proposals[replaced]=proposal;continue;}const key=p=>[compact(p.label),compact(p.rule),compact(p.unit),anchors(p)].join('|'),index=proposals.findIndex(p=>key(p)===key(proposal));if(index>=0)proposals[index]=proposal;else proposals.push(proposal);}return proposals;}
export async function discoverWorkbookCriteria(document,{gemini,withSandbox,signal,runId,contextId=document.id,report=()=>{},validateDiscovery,commonSystem=true}={}){
  if(document.kind!=='xlsx'||!document.buffer?.byteLength)throw new CriteriaSandboxError('INPUT','기준 탐색은 원본 XLSX 파일이 필요합니다.');
  const validator=validateDiscovery||(await import('./criteria-workbook-validation.mjs')).validateWorkbookDiscovery;
  return withSandbox(async(sandbox,sandboxReport)=>{
    const emit=event=>{sandboxReport(event);report(event);},abort=()=>{if(signal?.aborted)throw new CriteriaSandboxError('ABORTED','기준 탐색을 중단했습니다.');};
    const command=async(value,step,timeoutMs=45000)=>{abort();const result=await runObservedCommand(sandbox,value,{step,title:step==='install'?'기준 탐색 도구 준비':'기준 원문 범위 읽기',timeoutMs,requestTimeoutMs:timeoutMs+5000,signal,onActivity:emit,outputKind:step==='install'?'packages':'reader'});abort();if(result.exitCode!==0)throw new CriteriaSandboxError('READ','기준 원문 읽기를 완료하지 못했습니다.');};
    const readJson=async path=>{const raw=await sandbox.files.read(path);if(raw.length>1500000)throw new CriteriaSandboxError('LIMIT','기준 탐색 응답 크기 한도를 초과했습니다.');try{return JSON.parse(raw);}catch{throw new CriteriaSandboxError('READ','기준 탐색 응답 형식이 올바르지 않습니다.');}};
    await command('mkdir -p /home/user/trace-criteria','files');await sandbox.files.write([{path:'/home/user/trace-criteria/profile.py',data:readResourceText('server/criteria-workbook-profile.py')},{path:'/home/user/trace-criteria/workbook.xlsx',data:Uint8Array.from(document.buffer).buffer}]);
    await command('python -m pip install --disable-pip-version-check --no-input openpyxl==3.1.5','install',60000);
    let inventory=document.sandboxProfile?.criteriaInventory;if(!inventory){await command('python /home/user/trace-criteria/profile.py /home/user/trace-criteria/workbook.xlsx inventory /home/user/trace-criteria/inventory.json','inventory');inventory=await readJson('/home/user/trace-criteria/inventory.json');}
    if(!Array.isArray(inventory?.sheets)||!Array.isArray(inventory?.warnings))throw new CriteriaSandboxError('READ','기준 시트 목록을 확인하지 못했습니다.');
    emit({step:'plan',status:'running',title:'기준 범위 탐색 계획'});const plan=(await gemini.generateJson({role:'explore',schema:criteriaSchemas['criteria-sandbox.planSchema'],systemInstruction:systemInstruction('criteria-sandbox.SYSTEM',commonSystem),contents:[{text:prompt('criteria-sandbox.plan',{inventory})}],maxOutputTokens:5000,signal})).data;
    if(!Array.isArray(plan?.ranges)||!Array.isArray(plan?.regions)||!Array.isArray(plan?.warnings))throw new CriteriaSandboxError('FAILED','기준 탐색 계획 형식이 올바르지 않습니다.');
    const allRegions=inventory.sheets.flatMap(sheet=>sheet.regions.map(region=>({sheet:sheet.name,...region}))),records=new Map(),proposals=[],assessmentMap=new Map(),dispositions=[],seen=new Set(),warnings=[...inventory.warnings,...plan.warnings];let usedArea=0,detailComplete=true,remainingRanges=[],validation={criteria:[],omitted:[],unresolved:[],regionProblems:[],contextSignals:[],contextProblems:[],rejectedDispositions:[],validationErrors:[],droppedCriteria:0,classificationLimitReached:false,droppedHierarchyLevels:0},pending=[...plan.ranges,...allRegions.map(r=>({sheet:r.sheet,range:r.range}))],roundsRead=0;
    for(let rounds=0;rounds<2;rounds++){
      abort();const repeat=rounds>0&&!!(validation.omitted.length||validation.regionProblems.length||validation.contextProblems.length),selection=selectCriteriaRanges(pending,inventory,{usedArea,seen,repeat});usedArea=selection.usedArea;remainingRanges=selection.remainingRanges;if(selection.rejected.length){detailComplete=false;warnings.push('유효하지 않거나 한도를 초과한 기준 범위가 남아 있습니다.');}if(!selection.ranges.length)break;
      await sandbox.files.write('/home/user/trace-criteria/request.json',JSON.stringify({ranges:selection.ranges}));await command('python /home/user/trace-criteria/profile.py /home/user/trace-criteria/workbook.xlsx read /home/user/trace-criteria/details.json /home/user/trace-criteria/request.json','read');const details=await readJson('/home/user/trace-criteria/details.json');
      if(!Array.isArray(details.ranges)||details.ranges.length!==selection.ranges.length)throw new CriteriaSandboxError('READ','기준 상세 범위 응답이 요청과 일치하지 않습니다.');detailComplete&&=details.complete===true;
      for(let i=0;i<details.ranges.length;i++){const range=details.ranges[i],requested=selection.ranges[i],bounds=parseRange(requested.range);if(range.sheet!==requested.sheet||range.range!==requested.range||!Array.isArray(range.cells))throw new CriteriaSandboxError('READ','기준 상세 범위 응답이 요청과 일치하지 않습니다.');for(const cell of range.cells){if(!inRange(cell.cell,bounds)||typeof cell.text!=='string')throw new CriteriaSandboxError('READ','기준 상세 셀의 위치가 올바르지 않습니다.');records.set(`${range.sheet}\0${cell.cell}`,cell);}if(!range.truncated)seen.add(JSON.stringify(requested));}
      roundsRead++;emit({step:'extract',status:'running',attempt:rounds+1,maxAttempts:2,title:'전체 기준 후보 추출'});
      const extracted=(await gemini.generateJson({role:'extract',schema:criteriaSchemas['criteria-sandbox.extractSchema'],systemInstruction:systemInstruction('criteria-sandbox.SYSTEM',commonSystem),contents:[{text:prompt('criteria-sandbox.extract',{rounds,inventory,records,proposals,dispositions:dispositions.map(value=>({value})),...validation})}],maxOutputTokens:16000,signal})).data;
      if(!Array.isArray(extracted?.criteria)||!Array.isArray(extracted?.followUpRanges)||!Array.isArray(extracted?.warnings)||!Array.isArray(extracted?.regionAssessments)||!Array.isArray(extracted?.dispositions))throw new CriteriaSandboxError('FAILED','기준 후보 응답 형식이 올바르지 않습니다.');
      upsertCriteriaProposals(proposals,extracted.criteria);for(const assessment of extracted.regionAssessments)assessmentMap.set(assessment.id,assessment);dispositions.push(...extracted.dispositions);warnings.push(...extracted.warnings);
      validation=validator({document,inventory,records,proposals,regionAssessments:[...assessmentMap.values()],dispositions});
      const unread=allRegions.filter(r=>![...seen].map(JSON.parse).some(value=>value.sheet===r.sheet&&['start','end'].every(edge=>{const a=parseRange(r.range),b=parseRange(value.range);return inRange(a[edge].address,b);}))).map(r=>({sheet:r.sheet,range:r.range}));
      const problems=[...validation.omitted,...validation.unresolved,...validation.regionProblems,...validation.contextProblems].filter(p=>p&&p.sheet&&(p.range||p.cell)).map(p=>({sheet:p.sheet,range:p.range||p.cell}));pending=unique([...extracted.followUpRanges,...unread,...problems,...remainingRanges]);
      if(!pending.length&&!validation.omitted.length&&!validation.unresolved.length&&!validation.regionProblems.length&&!validation.contextProblems.length&&!validation.rejectedDispositions.length)break;
    }
    if(pending.length)remainingRanges=unique([...remainingRanges,...pending.filter(r=>!seen.has(JSON.stringify({sheet:r.sheet,range:parseRange(r.range)?.range||r.range}))) ]);
    const unresolvedRanges=unique([...remainingRanges,...[...validation.omitted,...validation.unresolved,...validation.regionProblems,...validation.contextProblems].filter(p=>p&&p.sheet&&(p.range||p.cell)).map(p=>({sheet:p.sheet,range:p.range||p.cell}))]),imagesNotRead=inventory.sheets.some(s=>s.images>0),criteriaLimitReached=validation.criteria.length>250||proposals.length>250,droppedCriteria=validation.droppedCriteria||0,criteria=validation.criteria.slice(0,250);
    if(imagesNotRead)warnings.push('기준 통합문서의 삽입 이미지는 탐색에서 판독하지 못했습니다.');
    const coverage={inventoryComplete:inventory.complete===true,allSheetsInventoried:inventory.sheets.every(s=>s.complete),allRegionsExamined:inventory.complete===true&&detailComplete&&allRegions.every(r=>assessmentMap.has(r.id)&&!validation.regionProblems.some(p=>p.id===r.id)),contextComplete:!validation.contextProblems.length&&!validation.rejectedDispositions.length,extractedCriteriaComplete:!validation.omitted.length&&!validation.unresolved.length&&!validation.regionProblems.length&&!validation.contextProblems.length&&!validation.rejectedDispositions.length&&detailComplete&&inventory.complete===true&&!droppedCriteria&&!criteriaLimitReached&&!remainingRanges.length,unresolvedRanges,remainingRanges,imagesNotRead,criteriaLimitReached,droppedCriteria,classificationLimitReached:!!validation.classificationLimitReached,droppedHierarchyLevels:validation.droppedHierarchyLevels||0,rounds:roundsRead,cellsRead:records.size,requestedArea:usedArea};
    return {criteria,inventory,coverage,warnings:[...new Set(warnings)].slice(0,100),regionAssessments:[...assessmentMap.values()],dispositions,rejectedDispositions:validation.rejectedDispositions};
  },{signal,timeoutMs:300000,activity:{kind:'criteria',title:'기준 통합문서 탐색',documentId:document.id,documentName:document.name,runId,contextId}});
}
