import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {snapshotRun,sourceItems,parseDashboardDesign,applyDashboardPreferences,renderDashboard,validateDashboardReport,createDashboardService,dashboardPrompt,sanitizeDiagnostic} from './dashboard.mjs';
const require=createRequire(import.meta.url);
async function cleanupDir(dir){const resolved=path.resolve(dir),root=path.resolve(os.tmpdir())+path.sep;if(!resolved.startsWith(root)||!path.basename(resolved).startsWith('gspec-dashboard-'))throw new Error('Refusing cleanup outside dashboard temporary fixtures');await rm(resolved,{recursive:true,force:true});}
async function executeValidator(dir){const source=await readFile(new URL('./assets/dashboard-validator.cjs',import.meta.url),'utf8');const scopedFs={statSync:p=>fs.statSync(path.join(dir,p)),readFileSync:(p,...args)=>fs.readFileSync(path.join(dir,p),...args),writeFileSync:(p,...args)=>fs.writeFileSync(path.join(dir,p),...args)};vm.runInNewContext(source,{require:name=>name==='node:fs'?scopedFs:require(name),console:{log(){}},process:{exitCode:0}},{timeout:120000});}
const run=()=>({id:'authored-run',status:'completed',criterionVersion:3,documents:[{id:'a',name:'<script>문서 & A.xlsx'},{id:'b',name:'B.csv'},{id:'empty',name:'빈 파일'}],items:Array.from({length:107},(_,n)=>({id:'item-'+n,documentId:n<104?'a':'b',criterionId:'c',label:n===0?'<script>alert(1)</script>':'밀도',value:String(n+1),unit:'g',criterion:'1 이상 · 단위: g · 조건: 실내',status:['pass','fail','pending'][n%3],explanation:'사유 <b>원문</b>',humanNote:'"확인" & 결과',reviewedByHuman:n===0,evidence:[{documentId:'a',page:1,quote:'</script><img src=x onerror=alert(1)>'}]}))});
test('snapshot is frozen, bounded and lossy exactly at the current allowlist',()=>{const raw=run();raw.items[0].presence='missing';raw.items[0].missingVerified=true;raw.items[0].value=null;const snapshot=snapshotRun(raw);assert.ok(Object.isFrozen(snapshot.items[0]));assert.equal(snapshot.items[0].value,'');assert.equal(snapshot.items[0].presence,undefined);assert.equal(snapshot.items[2].status,'review');assert.equal(snapshot.summary.documents,3);assert.equal(snapshot.summary.total,107);assert.equal(sourceItems(snapshot)[0].evidence.length,1);raw.items[1].status='fail';assert.equal(snapshot.items[1].status,'fail');raw.items[1].status='pass';assert.equal(snapshot.items[1].status,'fail');assert.ok(snapshot.numericGroups[0].values.length<=100);});
test('compatibility parser and baseline explicit preference behavior',()=>{const legacy={title:'',subtitle:'',accent:'cobalt',focus:'overview',density:'comfortable'};const design=parseDashboardDesign(legacy);assert.equal(design.distribution,'doughnut');assert.equal(design.theme,'dark');assert.throws(()=>parseDashboardDesign({...legacy,motion:null}));assert.throws(()=>parseDashboardDesign({...legacy,unknown:true}));assert.equal(applyDashboardPreferences(design,'Keep the dark page; make the charts light blue.').theme,'light');const changed=applyDashboardPreferences(design,'전체는 파이, 파일별 결과는 비교 막대로');assert.equal(changed.distribution,'bar');assert.equal(changed.fileVisualization,'bars');assert.equal(applyDashboardPreferences({...design,theme:'light'},'밤 테마').theme,'light');assert.equal(applyDashboardPreferences(design,'막대 말고 도넛').distribution,'doughnut');});
test('real standalone HTML passes fixed DOM/data validator for eight chart/theme combinations',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'gspec-dashboard-test-'));try{const input=run();input.items=input.items.slice(0,6);const snapshot=snapshotRun(input);for(const distribution of ['doughnut','pie','bar','polarArea'])for(const theme of ['dark','light']){const design=parseDashboardDesign({title:'시험 </script>',subtitle:'같은 검토 결과',accent:'#e8f199',focus:'exceptions',density:'compact',distribution,theme,legend:theme==='light'?'bottom':'hidden',chartSize:'large',motion:theme==='light'?'none':'subtle',corners:'square',fileVisualization:'bars'});const html=renderDashboard(snapshot,design);assert.equal((html.match(/<script nonce=/g)||[]).length,2);assert.ok(html.includes('react-chartjs-2'));await Promise.all([writeFile(path.join(dir,'dashboard.html'),html),writeFile(path.join(dir,'data.json'),JSON.stringify(snapshot)),writeFile(path.join(dir,'plan.json'),JSON.stringify(design))]);await executeValidator(dir);const rawReport=await readFile(path.join(dir,'validation.json'),'utf8');assert.deepEqual(JSON.parse(rawReport).diagnostics,[]);const report=validateDashboardReport(rawReport,snapshot);assert.equal(report.ok,true);assert.equal(report.visualBrowser,false);}}finally{await cleanupDir(dir);}});
test('plan context excludes quotes and files bytes; diagnostics redact',()=>{const snapshot=snapshotRun(run()),prompt=dashboardPrompt(snapshot,'밝게',undefined);assert.ok(!prompt.includes('onerror'));assert.ok(prompt.includes('UNTRUSTED DATA CONTEXT'));assert.equal(sanitizeDiagnostic('GEMINI_API_KEY=abc\nhttps://private/a\nplain'),'[민감 진단 숨김]\n[url]\nplain');});
test('parse repair and validation repair share three calls and reuse one sandbox/install',async()=>{const snapshot=snapshotRun(run()),files=new Map(),commands=[];let calls=0,sessions=0,validations=0;const plan={title:'검토 결과',subtitle:'동일한 판정',accent:'mint',focus:'overview',density:'comfortable'};const service=createDashboardService({gemini:{generateText:async()=>({text:++calls===1?'invalid':JSON.stringify(plan)})},withSandbox:async work=>{sessions++;return work({files:{write:async entries=>{for(const e of entries)files.set(e.path,e.data);},read:async name=>name.endsWith('validation.json')?JSON.stringify({version:1,ok:true,engine:'node-dom',visualBrowser:false,checks:Object.fromEntries(['input','syntax','csp','offline','kpis','charts','files','findings','filters','details','escaping'].map(c=>[c,true])),diagnostics:[],totals:snapshot.summary,files:2}):files.get(name)},commands:{run:async command=>{commands.push(command);if(command.endsWith('node validate.cjs')&&++validations===1)return {exitCode:1,stdout:'layout check failed',stderr:''};return {exitCode:0,stdout:'',stderr:''};}}},Object.assign(()=>{},{taskId:'sandbox-test'}));}});const job={id:'bounded',snapshot,instruction:'',attempt:0,logs:[],controller:new AbortController()};await service.generate(job);assert.equal(job.status,'ready');assert.equal(job.presentation,'generated');assert.equal(calls,3);assert.equal(sessions,1);assert.equal(commands.filter(c=>c.includes('npm install')).length,1);assert.equal(validations,2);assert.equal(job.html,files.get('/home/user/review-dashboard/dashboard.html'));});
test('a generated 107-item report exposes all rows through 100-item pagination',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'gspec-dashboard-many-'));try{const snapshot=snapshotRun(run()),design=parseDashboardDesign({title:'많은 항목',subtitle:'모든 항목 접근',accent:'cobalt',focus:'overview',density:'compact'});await Promise.all([writeFile(path.join(dir,'dashboard.html'),renderDashboard(snapshot,design)),writeFile(path.join(dir,'data.json'),JSON.stringify(snapshot)),writeFile(path.join(dir,'plan.json'),JSON.stringify(design))]);await executeValidator(dir);const raw=await readFile(path.join(dir,'validation.json'),'utf8');assert.deepEqual(JSON.parse(raw).diagnostics,[]);assert.equal(validateDashboardReport(raw,snapshot).totals.total,107);}finally{await cleanupDir(dir);}});
test('plan errors share budget, provider errors fallback, abort suppresses fallback',async()=>{const snapshot=snapshotRun(run()),legacy={title:'검토',subtitle:'결과',accent:'cobalt',focus:'overview',density:'comfortable'};let calls=0;const service=createDashboardService({gemini:{generateText:async()=>{calls++;return {text:'invalid'};}},engine:{}});const job={id:'j',snapshot,instruction:'파이',attempt:0,logs:[],controller:new AbortController()};await service.generate(job);assert.equal(calls,3);assert.equal(job.status,'ready');assert.equal(job.presentation,'standard');assert.equal(job.design.distribution,'pie');const cancelled={...job,id:'abort',html:undefined,attempt:0,logs:[],controller:new AbortController()};cancelled.controller.abort();await service.generate(cancelled);assert.equal(cancelled.status,'failed');assert.equal(cancelled.html,undefined);calls=0;const failService=createDashboardService({gemini:{generateText:async()=>{calls++;throw Object.assign(new Error('unavailable'),{name:'IntegrationError'});}}});await failService.generate({...job,id:'provider',attempt:0,logs:[],controller:new AbortController()});assert.equal(calls,1);});
