import { randomUUID } from 'node:crypto';
import { readResourceText } from './sites/resources.mjs';
import { normalizeDashboardDesign,applyDashboardPreferences } from './dashboard-design.mjs';
import { renderDashboard } from './dashboard-renderer.mjs';
import { observeActivity } from '../integrations/src/activity.mjs';
export { normalizeDashboardDesign,applyDashboardPreferences,renderDashboard };
export const dashboardSchema=JSON.parse(readResourceText('server/assets/dashboard-design.schema.json'));
const systemInstruction=readResourceText('server/assets/dashboard-system.txt');
const validator=readResourceText('server/assets/dashboard-validator.cjs');
const trim=(value,max)=>String(value??'').slice(0,max);
export function deepFreeze(value){if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(deepFreeze);}return value;}
export function snapshotRun(run,now=new Date().toISOString()) {
 const documents=(run.documents||[]).map(d=>({id:trim(d.id,100),name:trim(d.name,240)}));
 const items=(run.items||[]).map(item=>{const documentId=trim(item.documentId,100),sourceEvidence=(Array.isArray(item.evidence)?item.evidence:item.evidence?[item.evidence]:[]).slice(0,30).filter(e=>e&&typeof e==='object').map(e=>({documentId:trim(e.documentId||documentId,100),...(typeof e.page==='number'?{page:e.page}:{}),sheet:trim(e.sheet,120),cell:trim(e.cell,120),quote:trim(e.quote||e.text,800)}));const first=sourceEvidence[0]||{};return {id:trim(item.id,100),documentId,documentName:documents.find(d=>d.id===documentId)?.name||'',label:trim(item.label,240),value:trim(item.value,400),unit:trim(item.unit,100),criterionId:trim(item.criterionId,100),criterion:trim(item.criterion,800),status:['pass','compliant','적합'].includes(item.status)?'pass':['fail','noncompliant','부적합'].includes(item.status)?'fail':'review',explanation:trim(item.explanation,1600),reviewedByHuman:item.reviewedByHuman===true,humanNote:trim(item.humanNote,800),sourceEvidence,evidence:{page:typeof first.page==='number'?first.page:null,sheet:first.sheet||'',cell:first.cell||'',quote:first.quote||''}};});
 const summary={total:items.length,pass:items.filter(i=>i.status==='pass').length,fail:items.filter(i=>i.status==='fail').length,review:items.filter(i=>i.status==='review').length,humanReviewed:items.filter(i=>i.reviewedByHuman).length,documents:documents.length};
 const groups=new Map();for(const item of items){if(!item.criterionId||!item.label||!item.unit||!/^[+-]?(?:(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(item.value))continue;const value=Number(item.value.replaceAll(',',''));if(!Number.isFinite(value))continue;const key=JSON.stringify([item.criterionId,item.label,item.unit,item.criterion.trim()]);if(!groups.has(key))groups.set(key,{label:item.label,unit:item.unit,criterion:item.criterion.trim(),values:[]});groups.get(key).values.push({id:item.id,documentId:item.documentId,documentName:item.documentName,value});}
 const numericGroups=[...groups.values()].filter(g=>g.values.length>=2).slice(0,12).map(g=>({...g,total:g.values.length,values:g.values.slice(0,100)}));
 return deepFreeze({runId:trim(run.id,100),createdAt:now,criterionVersion:Number.isInteger(run.criterionVersion)?run.criterionVersion:1,partial:run.status==='partial',summary,documents,items,numericGroups});
}
export function sourceItems(snapshot){return deepFreeze(snapshot.items.map(({documentName,sourceEvidence,evidence,...item})=>({...item,evidence:sourceEvidence})));}
export function parseDashboardDesign(raw){let input=raw;if(typeof raw==='string'){if(raw.length>8000)throw new Error('디자인 응답이 너무 깁니다.');input=JSON.parse(raw.replace(/^\s*```(?:json)?\s*/i,'').replace(/\s*```\s*$/,''));}if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('디자인은 JSON 객체여야 합니다.');const properties=dashboardSchema.properties;if(Object.keys(input).some(key=>!Object.hasOwn(properties,key)))throw new Error('지원하지 않는 디자인 설정입니다.');for(const [key,schema]of Object.entries(properties)){const value=input[key];if(value===undefined&&!['title','subtitle','accent','focus','density'].includes(key))continue;if(typeof value!=='string'||schema.maxLength&&value.length>schema.maxLength||schema.enum&&!schema.enum.includes(value)||schema.pattern&&!new RegExp(schema.pattern).test(value))throw new Error(`${key} 디자인 설정이 올바르지 않습니다.`);}return normalizeDashboardDesign(input);}
export function sanitizeDiagnostic(value,secrets=[]){let text=String(value??'').replace(/\x1B\[[0-?]*[ -/]*[@-~]/g,'');for(const secret of secrets)if(secret)text=text.split(secret).join('[redacted]');return text.split(/\r?\n/).map(line=>/key|authorization|process\.env|environ|GEMINI_|E2B_|password|secret|token|\b[A-Z_][A-Z0-9_]*\s*=/i.test(line)?'[민감 진단 숨김]':line).join('\n').replace(/AIza[\w-]+|e2b_[\w-]+|Bearer\s+\S+/g,'[redacted]').replace(/https?:\/\/[^\s<>"']+/g,'[url]').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g,'');}
export function dashboardPrompt(snapshot,instruction,baseDesign,previous,diagnostic){const context={summary:snapshot.summary,partial:snapshot.partial,reviewedFiles:snapshot.documents.filter(d=>snapshot.items.some(i=>i.documentId===d.id)).slice(0,12).map(d=>d.name),exampleLabels:[...new Set(snapshot.items.map(i=>i.label))].slice(0,12)};return `DESIGN REQUEST:\n${instruction||'파일별 결과를 쉽게 이해할 수 있게 차트 중심으로 정리해 주세요.'}\n${baseDesign?`CURRENT DESIGN (retain choices the user did not ask to change):\n${JSON.stringify(normalizeDashboardDesign(baseDesign))}\n`:''}UNTRUSTED DATA CONTEXT:\n${JSON.stringify(context)}${previous||diagnostic?`\nPrevious design plan: ${String(previous||'').slice(0,8000)}\nValidation feedback (fix only supported plan choices): ${String(diagnostic).slice(0,3000)}`:''}`;}
export function validateDashboardReport(raw,snapshot){if(typeof raw!=='string'||!raw.length||raw.length>32000)throw new Error('대시보드 검사 보고서가 올바르지 않습니다.');const report=JSON.parse(raw);const checks=['input','syntax','csp','offline','kpis','charts','files','findings','filters','details','escaping'];if(report.version!==1||report.ok!==true||report.engine!=='node-dom'||report.visualBrowser!==false||checks.some(c=>report.checks?.[c]!==true)||!Array.isArray(report.diagnostics)||report.diagnostics.length||['total','pass','fail','review'].some(c=>report.totals?.[c]!==snapshot.summary[c])||report.files!==new Set(snapshot.items.map(i=>i.documentId)).size)throw new Error('대시보드 검사 결과가 검토 데이터와 일치하지 않습니다.');return report;}
const abortCheck=signal=>{if(signal.aborted)throw Object.assign(new Error('대시보드 생성을 취소했습니다.'),{name:'AbortError'});};
export function createDashboardService({engine,gemini,withSandbox,config,activityStore,deferExecution=false}={}) {
 const jobs=new Map();let active=null;
 const publicJob=job=>{const result={id:job.id,status:job.status,message:job.message,attempt:job.attempt,logs:job.logs,criterionVersion:job.snapshot.criterionVersion};if(deferExecution&&!['ready','failed'].includes(job.status))result.eventsUrl=`/api/dashboards/${encodeURIComponent(job.id)}/events`;if(job.status==='ready')Object.assign(result,{sourceItems:sourceItems(job.snapshot),presentation:job.presentation||'generated',design:job.design});if(job.html!==undefined)result.html=job.html;if(job.error!==undefined)result.error=job.error;return result;};
 const log=(job,step,status,title,detail,output)=>{const clean=value=>sanitizeDiagnostic(value,[config?.geminiApiKey,config?.e2bApiKey]);job.logs.push({id:randomUUID(),time:new Date().toISOString(),step,status,title:clean(title).slice(0,160),...(detail?{detail:clean(detail).slice(0,500)}:{}),...(output?{output:clean(output).slice(0,1500)}:{})});job.logs=job.logs.slice(-80);};
 // Persist only data: controllers and promises belong to the request executing the job.
 function serializeJob(jobOrId){const job=typeof jobOrId==='string'?jobs.get(jobOrId):jobOrId;if(!job)return null;const fields=['id','status','message','attempt','logs','snapshot','instruction','baseDesign','pending','presentation','design','html','validation','error'];return JSON.parse(JSON.stringify(Object.fromEntries(fields.filter(key=>job[key]!==undefined).map(key=>[key,job[key]]))));}
 // Read-only requests inspect executing jobs; only an expired lease owner recovers them.
 function hydrateJob(record,{recoverInterrupted=false}={}){if(!record||typeof record.id!=='string'||!record.snapshot||!Array.isArray(record.snapshot.items))throw new Error('저장된 대시보드 작업이 올바르지 않습니다.');const existing=jobs.get(record.id);if(existing?.work)return existing;const job={...serializeJob(record),controller:new AbortController()};job.snapshot=deepFreeze(job.snapshot);job.logs=Array.isArray(job.logs)?job.logs.slice(-80):[];job.attempt=Number.isInteger(job.attempt)?job.attempt:0;if(!['ready','failed'].includes(job.status)){if(job.pending?.state==='queued'){job.status='queued';active=job.id;}else if(!recoverInterrupted&&job.pending?.state==='executing'){active=job.id;}else{job.status='failed';job.message='대시보드 생성 연결이 중단되었습니다. 다시 구성해 주세요.';job.error=job.message;delete job.pending;if(active===job.id)active=null;log(job,'build','failed','대시보드 생성 중단',job.message);}}else{delete job.pending;if(active===job.id)active=null;}jobs.set(job.id,job);return job;}
 const serializeJobs=()=>[...jobs.values()].map(serializeJob);
 function hydrateJobs(records,options){if(!Array.isArray(records))throw new Error('저장된 대시보드 목록이 올바르지 않습니다.');return records.map(record=>hydrateJob(record,options));}
 function deleteJob(id){const job=jobs.get(id);if(!job)return false;job.controller.abort();jobs.delete(id);if(active===id)active=null;return true;}
 // Durable adapters save the executing marker before any potentially billed operation.
 function executePendingJob(jobOrId,{beforeExecute}={}){const job=typeof jobOrId==='string'?jobs.get(jobOrId):jobOrId;if(!job)throw Object.assign(new Error('대시보드를 찾을 수 없습니다.'),{status:404});if(job.work)return job.work;if(['ready','failed'].includes(job.status)||job.pending?.state!=='queued')return Promise.resolve(job);job.work=Promise.resolve().then(async()=>{job.pending={state:'executing'};try{await beforeExecute?.(job);}catch(error){job.pending={state:'queued'};throw error;}await generate(job);return job;}).finally(()=>{if(['ready','failed'].includes(job.status))delete job.pending;delete job.work;});return job.work;}
 async function generate(job){const {snapshot,instruction,baseDesign}=job,signal=job.controller.signal;let previous='',diagnostic='',design,lastTaskId;async function plan(){while(job.attempt<3){abortCheck(signal);job.attempt++;job.status=job.attempt===1?'generating':'repairing';job.message=job.attempt===1?'요청한 화면 구성을 준비하고 있습니다.':'검사 결과를 반영해 구성을 보완하고 있습니다.';log(job,'model','running','화면 구성 계획',null);try{if(!gemini?.generateText)throw Object.assign(new Error('화면 구성 서비스를 사용할 수 없습니다.'),{name:'IntegrationError'});const response=await observeActivity({kind:'dashboard',runtime:'gemini',title:'화면 구성 계획',runId:snapshot.runId,contextId:job.id,attempt:job.attempt,maxAttempts:3},async report=>{if(lastTaskId&&report.taskId)report({step:'model',status:'running',title:'화면 구성 계획',handoff:{fromTaskId:lastTaskId,toTaskId:report.taskId}});lastTaskId=report.taskId;return gemini.generateText({prompt:dashboardPrompt(snapshot,instruction,baseDesign,previous,diagnostic),role:'explore',schema:dashboardSchema,systemInstruction,maxOutputTokens:2000,signal});},{signal,...(activityStore?{store:activityStore}:{})});abortCheck(signal);previous=response.text;design=applyDashboardPreferences(parseDashboardDesign(response.text),instruction);previous=JSON.stringify(design);log(job,'model','completed','화면 구성 계획 완료');return design;}catch(error){abortCheck(signal);log(job,'model','failed','화면 구성 계획 실패',error.message);if(error.name==='IntegrationError')throw error;diagnostic=sanitizeDiagnostic(error.message);if(job.attempt>=3)throw error;}}throw new Error('화면 구성 재시도 횟수를 초과했습니다.');}
 try{await plan();abortCheck(signal);if(!withSandbox)throw new Error('화면 검사 서비스를 사용할 수 없습니다.');log(job,'prepare','running','화면 검사 환경 준비');const result=await withSandbox(async(sandbox,report)=>{const root='/home/user/review-dashboard';if(lastTaskId&&report?.taskId)report({step:'prepare',status:'running',title:'화면 검사 환경 준비',handoff:{fromTaskId:lastTaskId,toTaskId:report.taskId}});lastTaskId=report?.taskId;const command=async(command,timeoutMs,step,title)=>{log(job,step,'running',title);report?.({step,status:'running',title});const result=await sandbox.commands.run(command,{timeoutMs,requestTimeoutMs:timeoutMs});abortCheck(signal);log(job,step,result.exitCode===0?'completed':'failed',title,null,result.stdout||result.stderr);report?.({step,status:result.exitCode===0?'completed':'failed',title});if(result.exitCode!==0)throw new Error(sanitizeDiagnostic(result.stderr||result.stdout||'화면 검사 명령이 실패했습니다.'));return result;};await command(`mkdir -p ${root}`,20000,'prepare','화면 검사 환경 준비');log(job,'files','running','검사 자료 준비');await sandbox.files.write([{path:root+'/package.json',data:JSON.stringify({private:true,dependencies:{jsdom:'26.1.0'}})},{path:root+'/validate.cjs',data:validator},{path:root+'/data.json',data:JSON.stringify(snapshot)}]);log(job,'files','completed','검사 자료 준비 완료');await command(`cd ${root} && npm install --no-audit --no-fund --ignore-scripts`,60000,'install','화면 검사 도구 준비');while(true){abortCheck(signal);job.status='building';job.message='검토 결과로 화면을 구성하고 있습니다.';log(job,'build','running','대시보드 화면 구성');const html=renderDashboard(snapshot,design);if(html.length<1000||html.length>8000000)throw new Error('화면 파일 크기가 허용 범위를 벗어났습니다.');await sandbox.files.write([{path:root+'/dashboard.html',data:html},{path:root+'/plan.json',data:JSON.stringify(design)}]);log(job,'build','completed','대시보드 화면 구성 완료');try{await command(`cd ${root} && node validate.cjs`,20000,'validate','대시보드 데이터와 동작 검사');const report=validateDashboardReport(await sandbox.files.read(root+'/validation.json'),snapshot);if(await sandbox.files.read(root+'/dashboard.html')!==html)throw new Error('검사한 화면 파일이 생성한 화면과 다릅니다.');abortCheck(signal);return {html,design,validation:report};}catch(error){abortCheck(signal);if(job.attempt>=3)throw error;diagnostic=sanitizeDiagnostic(error.message);log(job,'repair','running','검사 결과에 맞춰 화면 보완',diagnostic);await plan();}}},{config,timeoutMs:240000,signal,activity:{kind:'dashboard',title:'대시보드 화면 검사',runId:snapshot.runId,contextId:job.id,attempt:job.attempt,maxAttempts:3}});log(job,'cleanup','completed','화면 검사 환경 정리 완료');abortCheck(signal);Object.assign(job,result,{status:'ready',message:'대시보드 구성이 완료되었습니다.',presentation:'generated'});
 }catch(error){if(signal.aborted){job.status='failed';job.message='대시보드 생성을 취소했습니다.';job.error=job.message;return;}log(job,error.code==='CLEANUP_FAILED'?'cleanup':'build','failed',error.code==='CLEANUP_FAILED'?'화면 검사 환경 정리 실패':'맞춤 화면 구성 실패',error.message);try{const design=applyDashboardPreferences(baseDesign||{},instruction),html=renderDashboard(snapshot,design,{presentation:'standard'});abortCheck(signal);Object.assign(job,{status:'ready',presentation:'standard',design,html,message:'요청한 구성을 완성하지 못해 기본 자동 시각화로 표시합니다.'});log(job,'validate','info','맞춤 구성의 샌드박스 검사는 완료되지 않았습니다.');}catch{job.status='failed';job.message='대시보드 표시 파일을 준비하지 못했습니다. 기본 검토 결과에서 판정을 확인해 주세요.';job.error=job.message;}}finally{if(active===job.id)active=null;}}
 function registerRoutes(router){router.post('/api/dashboards',(req,res)=>{if(active)return res.status(409).json({error:'대시보드를 생성하고 있습니다. 잠시 후 다시 시도하세요.'});const {runId,instruction,baseDesign}=req.body||{};if(typeof runId!=='string'||runId.length>100||instruction!==undefined&&(typeof instruction!=='string'||instruction.length>1500))return res.status(400).json({error:'검토 ID와 1,500자 이내의 화면 요청을 입력하세요.'});let run;try{run=engine.get?.(runId)??engine.runs?.get(runId);}catch(error){if(error.status!==404)throw error;}if(!run)return res.status(404).json({error:'검토 결과를 찾을 수 없습니다.'});if(!['completed','partial'].includes(run.status))return res.status(409).json({error:'검토를 완료한 후 대시보드를 만들 수 있습니다.'});if(!run.items?.length||run.items.length>2000)return res.status(409).json({error:'대시보드에는 1~2000개의 검토 항목이 필요합니다.'});let base;try{if(baseDesign!==undefined)base=parseDashboardDesign(baseDesign);}catch{return res.status(400).json({error:'이전 대시보드의 디자인 구성이 올바르지 않습니다.'});}if(jobs.size>=10){const old=[...jobs].find(([,j])=>['ready','failed'].includes(j.status));if(old)jobs.delete(old[0]);}const job={id:randomUUID(),status:'queued',message:'대시보드 생성 요청을 준비하고 있습니다.',attempt:0,logs:[],snapshot:snapshotRun(run),instruction:instruction||'',baseDesign:base,pending:{state:'queued'},controller:new AbortController()};jobs.set(job.id,job);active=job.id;res.status(202).json(publicJob(job));if(!deferExecution)void executePendingJob(job);});router.get('/api/dashboards/:id',(req,res)=>{const job=jobs.get(req.params.id);if(!job)return res.status(404).json({error:'대시보드를 찾을 수 없습니다.'});res.setHeader('Cache-Control','no-store');res.json(publicJob(job));});router.delete('/api/dashboards/:id',(req,res)=>{const job=jobs.get(req.params.id);if(!job)return res.status(404).json({error:'대시보드를 찾을 수 없습니다.'});deleteJob(job.id);res.status(204).end();});}
 return {registerRoutes,jobs,publicJob,generate,serializeJob,hydrateJob,serializeJobs,hydrateJobs,executePendingJob,deleteJob};
}
