import ExcelJS from 'exceljs';
import { LedgerError,analyzeLedger,writeLedgerCopy,createLedgerProposal } from './ledger.mjs';
import { createDashboardService } from './dashboard.mjs';

const labels={pass:'적합',fail:'부적합',review:'확인 필요'};
export function summarizeRun(run){const items=run.items||[],documents=run.documents||[];return {total:items.length,pass:items.filter(i=>i.status==='pass').length,fail:items.filter(i=>i.status==='fail').length,review:items.filter(i=>i.status==='review').length,documents:documents.length,completedDocuments:documents.filter(d=>d.status==='completed').length,failedDocuments:documents.filter(d=>d.status==='failed').length,incompleteDocuments:documents.filter(d=>d.status==='partial').length,unreviewedRows:documents.reduce((n,d)=>n+(d.missingRows?.length??0),0),humanReviewed:items.filter(i=>i.reviewedByHuman).length};}
export const EXPORT_HEADERS=['문서','항목','추출값','단위','적용 기준','최종 판정','AI 원판정','판정 이유','원문 근거','사람 검토 사유','사람 확인'];
export function exportRows(run){return run.items.map(item=>[(run.documents||[]).find(d=>d.id===item.documentId)?.name??item.documentId,item.label,item.value,item.unit,item.criterion,labels[item.status]??item.status,labels[item.machineStatus]??item.machineStatus,item.explanation,(Array.isArray(item.evidence)?item.evidence:item.evidence?[item.evidence]:[]).map(e=>[e.page&&`${e.page}쪽`,e.sheet,e.cell,e.quote].filter(Boolean).join(' · ')).join('\n'),item.humanNote??'',item.reviewedByHuman?'예':'아니오']);}
export function exportCSV(run){const cell=value=>{let out=String(value??'');if(/^[\s]*[=+@-]/.test(out))out="'"+out;return '"'+out.replaceAll('"','""')+'"';};return '\uFEFF'+[EXPORT_HEADERS,...exportRows(run)].map(row=>row.map(cell).join(',')).join('\r\n');}
export function exportJSON(run){const out={};for(const key of ['id','mode','status','createdAt','criterionVersion','approvedCriteria','criteriaFeedback','summary','criteria','criteriaDiscovery','analyses','documents','items','audit']){if(key==='summary')out[key]=run.summary??summarizeRun(run);else if(key==='documents')out[key]=(run.documents||[]).map(({buffer,modelParts,...document})=>document);else out[key]=run[key];}return JSON.stringify(out,null,2);}
export async function exportXLSX(run){const workbook=new ExcelJS.Workbook();workbook.creator='REVIEW / Universal Reviewer';const results=workbook.addWorksheet('검토 결과');results.addRows([EXPORT_HEADERS,...exportRows(run)]);results.views=[{state:'frozen',ySplit:1}];[26,30,18,12,44,14,14,60,60,40,14].forEach((width,n)=>results.getColumn(n+1).width=width);results.getRow(1).eachCell(cell=>{cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1D3632'}};});results.eachRow(row=>row.alignment={vertical:'top',wrapText:true});const criteria=workbook.addWorksheet('적용 기준');criteria.addRows([['ID','기준명','적용 규칙','출처'],...(run.criteria||[]).map(c=>[c.id,c.label,c.rule,c.source])]);[12,30,80,45].forEach((width,n)=>criteria.getColumn(n+1).width=width);const audit=workbook.addWorksheet('확인 이력');audit.addRows([['동작','시각','항목','변경 전','변경 후','사유'],...(run.audit||[]).map(a=>[a.action,a.timestamp,a.itemId??'',a.before??'',a.after??'',a.note??''])]);const scope=workbook.addWorksheet('검토 범위');scope.addRows([['검토 ID',run.id],['완료 상태',run.status],['기준 버전',run.criterionVersion],['안내','확인 필요 및 처리 실패 문서를 검토하세요. AI 원판정과 사람의 수정 이력이 함께 보존됩니다.'],[],['문서','처리 상태','오류'],...(run.documents||[]).map(d=>[d.name,d.status,d.error??''])]);[35,65,65].forEach((width,n)=>scope.getColumn(n+1).width=width);return Buffer.from(await workbook.xlsx.writeBuffer());}
export function createExportService(deps){return {dashboard:createDashboardService(deps),summary:summarizeRun,rows:exportRows,json:exportJSON,csv:exportCSV,xlsx:exportXLSX};}
const attachment=(res,fallback,name)=>res.setHeader('Content-Disposition',`attachment; filename="${fallback}"; filename*=UTF-8''${encodeURIComponent(name)}`);
export function registerRoutes(router,deps){const {documents,engine}=deps;const service=createExportService(deps);const getRun=id=>{try{return engine.get?.(id)??engine.runs?.get(id);}catch(error){if(error.status===404)return undefined;throw error;}};const safe=handler=>async(req,res)=>{try{await handler(req,res);}catch(error){if(!res.headersSent)res.status(error instanceof LedgerError?error.status:500).json({error:error instanceof LedgerError?error.message:'검토대장 처리 중 오류가 발생했습니다.'});}};
 router.get('/api/runs/:id/export',async(req,res)=>{try{const run=getRun(req.params.id);if(!run)return res.status(404).json({error:'검토 결과를 찾을 수 없습니다.'});if(!['completed','partial','failed'].includes(run.status)||!run.items?.length)return res.status(409).json({error:'내보낼 검토 결과가 아직 없습니다.'});const format=req.query.format??'json';if(!['json','csv','xlsx'].includes(format))return res.status(400).json({error:'내보내기는 json, csv, xlsx를 지원합니다.'});const value=await service[format](run);attachment(res,`review-export.${format}`,`검토결과_${run.id.slice(0,8)}.${format}`);res.type({json:'application/json;charset=utf-8',csv:'text/csv;charset=utf-8',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}[format]).send(value);}catch{res.status(500).json({error:'검토 결과를 내보내지 못했습니다.'});}});
 async function analyzed(req,res){let document;try{document=documents.get(req.body.documentId);}catch(error){if(error.status!==404)throw error;}if(!document||document.kind!=='xlsx')throw new LedgerError('XLSX 검토대장을 찾을 수 없습니다.',404);if(req.body.contextId!==undefined&&(typeof req.body.contextId!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(req.body.contextId)))throw new LedgerError('작업 식별자가 올바르지 않습니다.');const controller=new AbortController();const abort=()=>controller.abort();const close=()=>{if(!res.writableEnded)abort();};req.on('aborted',abort);res.on('close',close);try{const ensure=deps.ensureAnalyzed??documents.ensureAnalyzed?.bind(documents);const analysis=ensure?await ensure(document,{contextId:req.body.contextId,signal:controller.signal}):undefined;return {document,analysis:analysis?.analysis??analysis};}finally{req.off('aborted',abort);res.off('close',close);}}
 router.post('/api/ledgers/analyze',safe(async(req,res)=>{const {document,analysis}=await analyzed(req,res);const mapping=await analyzeLedger(document.buffer,req.body.key);const proposal=req.body.runId||req.body.sourceDocumentId?createLedgerProposal(getRun(req.body.runId),req.body.sourceDocumentId):undefined;res.json({mapping,...(proposal?{proposal}:{}),...(analysis?{analysis}:{} )});}));
 router.post('/api/ledgers/export',safe(async(req,res)=>{const body=req.body;if(body.confirmed!==true)throw new LedgerError('기록할 성적서번호·판정·비고·대상 셀을 확인해 주세요.');const {document}=await analyzed(req,res);if(typeof body.key!=='string'||body.mapping?.key!==body.key.trim())throw new LedgerError('성적서번호와 기록 위치를 다시 확인해 주세요.');const proposal=createLedgerProposal(getRun(body.runId),body.sourceDocumentId);if(body.proposalFingerprint!==proposal.fingerprint)throw new LedgerError('검토 결과가 변경되었습니다. 기입 내용을 다시 확인해 주세요.',409);if(body.note!==undefined&&(typeof body.note!=='string'||body.note.length>1000))throw new LedgerError('추가 의견은 1,000자 이내로 입력해 주세요.');const note=proposal.note+(body.note?.trim()?`\n사용자 확인: ${body.note.trim()}`:'');const buffer=await writeLedgerCopy(document.buffer,body.mapping,proposal.result,note);attachment(res,'review-ledger.xlsx',document.name.replace(/\.xlsx$/i,'')+'_검토반영.xlsx');res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(buffer);}));
 service.dashboard.registerRoutes(router);return service;
}
