import test from 'node:test';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import {EventEmitter} from 'node:events';
import {exportCSV,exportJSON,exportXLSX,registerRoutes} from './exports.mjs';
const makeRun=()=>({id:'independent-run',status:'partial',mode:'criteria_first',criterionVersion:2,createdAt:'2026-01-01T00:00:00Z',documents:[{id:'a',name:'한글.csv',status:'completed',buffer:Buffer.from('must-not-export'),modelParts:['private']},{id:'b',name:'실패.pdf',status:'failed',error:'판독 실패'}],criteria:[{id:'c',label:'밀도',rule:'1 이상',source:'기준서'}],items:[{id:'i',documentId:'a',label:'=1+1',value:'"인용"\n둘째',unit:'g',criterion:'1 이상',status:'fail',machineStatus:'pass',explanation:'사람 확인',humanNote:'단위 확인',reviewedByHuman:true,evidence:[{page:2,sheet:'표',cell:'B2',quote:'원문,인용'}]}],audit:[{action:'item.resolved',timestamp:'now',itemId:'i',before:'pass',after:'fail',note:'단위 확인'}]});
test('CSV quotes all cells, keeps BOM/CRLF, neutralizes spreadsheet formulas',()=>{const csv=exportCSV(makeRun());assert.equal(csv[0],'\uFEFF');assert.ok(csv.includes('"\'=1+1"'));assert.ok(csv.includes('"""인용""\n둘째"'));assert.ok(csv.includes('\r\n'));assert.ok(csv.includes('"2쪽 · 표 · B2 · 원문,인용"'));assert.ok(csv.includes('"부적합","적합"'));});
test('JSON and workbook keep final and machine judgments and audit, exclude buffers',async()=>{const run=makeRun(),data=JSON.parse(exportJSON(run));assert.equal(data.documents[0].buffer,undefined);assert.equal(data.documents[0].modelParts,undefined);assert.equal(data.items[0].machineStatus,'pass');const w=new ExcelJS.Workbook();await w.xlsx.load(await exportXLSX(run));assert.deepEqual(w.worksheets.map(s=>s.name),['검토 결과','적용 기준','확인 이력','검토 범위']);assert.equal(w.creator,'REVIEW / Universal Reviewer');assert.equal(w.worksheets[0].getCell('F2').value,'부적합');assert.equal(w.worksheets[0].getCell('G2').value,'적합');assert.equal(w.worksheets[0].getCell('B2').type,ExcelJS.ValueType.String);assert.equal(w.worksheets[2].getCell('F2').value,'단위 확인');assert.equal(w.worksheets[3].getCell('C8').value,'판독 실패');assert.equal(w.worksheets[0].views[0].ySplit,1);});
test('export route status gates and unknown format',async()=>{let run=makeRun();const routes=new Map(),router={get:(p,f)=>routes.set('GET '+p,f),post(){},delete(){}};registerRoutes(router,{engine:{get:()=>run},documents:{get(){}}});const call=async(format)=>{const out={code:200};const res={status(n){out.code=n;return this;},json(v){out.body=v;return this;},setHeader(){return this;},type(){return this;},send(v){out.body=v;return this;}};await routes.get('GET /api/runs/:id/export')({params:{id:'x'},query:format?{format}:{}},res);return out;};run.status='running';assert.equal((await call()).code,409);run.status='failed';assert.equal((await call('bad')).code,400);assert.equal((await call('json')).code,200);run.items=[];assert.equal((await call('json')).code,409);run=undefined;assert.equal((await call()).code,404);});
async function ledgerApi(ensureAnalyzed){const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('기록');sheet.addRow(['성적서번호','판정','비고']);sheet.addRow(['R42']);const document={id:'ledger',kind:'xlsx',name:'내 기록.XLSX',buffer:Buffer.from(await workbook.xlsx.writeBuffer())},run=makeRun();const routes=new Map(),router={get:(p,f)=>routes.set('GET '+p,f),post:(p,f)=>routes.set('POST '+p,f),delete:(p,f)=>routes.set('DELETE '+p,f)};registerRoutes(router,{documents:{get:id=>{if(id==='ledger')return document;throw Object.assign(new Error('missing'),{status:404});}},engine:{get:()=>run},ensureAnalyzed});const request=(route,body)=>{const req=Object.assign(new EventEmitter(),{body}),out={code:200,headers:{}},res=Object.assign(new EventEmitter(),{writableEnded:false,status(n){out.code=n;return this;},json(v){out.body=v;this.writableEnded=true;return this;},setHeader(k,v){out.headers[k]=v;return this;},type(){return this;},send(v){out.body=v;this.writableEnded=true;return this;}});return {req,res,out,work:routes.get('POST '+route)(req,res)};};return {request,run,document};}
test('ledger HTTP fingerprints proposal, preserves human-note-only changes and ignores client result',async()=>{let analyzed=0;const publicAnalysis={status:'partial',summary:'일부 구조 확인',warnings:[],needsConfirmation:true,coverage:{complete:false,readerComplete:true,contextComplete:false}};const api=await ledgerApi(async()=>{analyzed++;return publicAnalysis;});const body={documentId:'ledger',runId:'independent-run',sourceDocumentId:'a',key:'R42',contextId:'ctx-one'},analysis=api.request('/api/ledgers/analyze',body);await analysis.work;assert.equal(analysis.out.code,200);assert.deepEqual(analysis.out.body.analysis,publicAnalysis);assert.equal(analysis.out.body.sourceSheets,undefined);assert.equal(analysis.out.body.mapping.status,'ready');const exportBody={...body,mapping:analysis.out.body.mapping,proposalFingerprint:analysis.out.body.proposal.fingerprint,confirmed:true,result:'적합',note:'=HYPERLINK("x")'};api.run.items[0].humanNote='다른 사람 메모';const exported=api.request('/api/ledgers/export',exportBody);await exported.work;assert.equal(exported.out.code,200);const w=new ExcelJS.Workbook();await w.xlsx.load(exported.out.body);assert.equal(w.worksheets[0].getCell('B2').value,'부적합');assert.ok(w.worksheets[0].getCell('C2').value.endsWith('사용자 확인: =HYPERLINK("x")'));api.run.items[0].status='pass';const stale=api.request('/api/ledgers/export',exportBody);await stale.work;assert.equal(stale.out.code,409);assert.equal(analyzed,3);});
test('ledger HTTP validates confirmation before lookup, missing docs404, and aborts only its own analysis',async()=>{let captured;const api=await ledgerApi(async(_,{signal,contextId})=>{captured={signal,contextId};await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}));});const noConfirm=api.request('/api/ledgers/export',{documentId:'missing'});await noConfirm.work;assert.equal(noConfirm.out.code,400);const missing=api.request('/api/ledgers/analyze',{documentId:'missing'});await missing.work;assert.equal(missing.out.code,404);const pending=api.request('/api/ledgers/analyze',{documentId:'ledger',key:'R42',contextId:'scope-one'});assert.equal(captured.contextId,'scope-one');pending.res.emit('close');await pending.work;assert.equal(captured.signal.aborted,true);assert.equal(pending.req.listenerCount('aborted'),0);assert.equal(pending.res.listenerCount('close'),0);assert.equal(pending.out.code,500);});
