import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source=ts.transpileModule(fs.readFileSync(new URL('../activity-model.ts',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {handoffCandidates,HandoffQueue,workStage,preferredTask,normalizeActivity,scopeActivity,activityGroups}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const at='2026-09-21T12:00:00.000Z';
function task(id,runtime,extra={}){return {id,runtime,documentId:'doc',runId:'run',status:'running',phase:'read',kind:'document',startedAt:at,events:[],...extra};}
test('a parent and explicit receiver start describe one transfer, while logs and neighboring runtimes do not',()=>{const from=task('a','e2b');const start={id:'start',time:at,status:'running',title:'읽기',step:'read'};const to=task('b','gemini',{parentTaskId:'a',events:[start,{...start,id:'explicit',handoff:{fromTaskId:'a',toTaskId:'b'}}]});assert.equal(handoffCandidates([from,to]).length,1);assert.equal(handoffCandidates([from,task('c','gemini')]).length,0);assert.equal(handoffCandidates([from,{...to,events:[{...start,log:true}]}]).length,0);});
test('cross-run and same-runtime witnesses cannot animate a transfer',()=>{const event={id:'start',time:at,status:'running',title:'읽기',step:'read'};const from=task('a','e2b');assert.equal(handoffCandidates([from,task('b','gemini',{parentTaskId:'a',runId:'other',events:[event]})]).length,0);assert.equal(handoffCandidates([from,task('b','e2b',{parentTaskId:'a',events:[event]})]).length,0);});
test('backlog remains bounded and clearing does not replay received transfers',()=>{const queue=new HandoffQueue();const values=Array.from({length:20},(_,i)=>({key:`H${i+1}`,time:i,sequence:i}));queue.enqueue(values);assert.equal(queue.omitted,12);assert.equal(queue.take().key,'H13');queue.clearPending();queue.enqueue(values);assert.equal(queue.pending.length,0);queue.reset();queue.enqueue(values.slice(0,1));assert.equal(queue.take().key,'H1');});
test('waiting tasks do not displace executing work and model/repair stages follow runtime semantics',()=>{const executing=task('a','e2b');const waiting=task('b','gemini',{startedAt:'2026-09-21T12:00:05Z',waitingForTaskId:'c'});assert.equal(preferredTask([waiting,executing]).id,'a');assert.equal(workStage(task('c','gemini',{kind:'dashboard',phase:'repair'})),2);assert.equal(workStage(task('d','gemini',{phase:'model'})),3);assert.equal(workStage(task('e','e2b',{phase:'read',status:'queued'})),0);});
test('snapshot limits preserve the baseline tail and validate event titles after slicing',()=>{const tasks=Array.from({length:150},(_,index)=>task(String(index),'e2b'));tasks[149].events=Array.from({length:201},(_,index)=>({title:index===200?'':String(index)}));const normalized=normalizeActivity(tasks);assert.equal(normalized.length,100);assert.equal(normalized[0].id,'50');assert.equal(normalized.at(-1).events.length,199);assert.equal(normalized.at(-1).events[0].title,'1');});
test('scope is conjunctive before parent grouping; grouping does not invent missing scope identifiers',()=>{const parent=task('parent','e2b',{contextId:'A'}),child=task('child','gemini',{documentId:undefined,contextId:'B',parentTaskId:'parent'}),orphan=task('orphan','gemini',{runId:undefined,parentTaskId:'parent',documentId:undefined});assert.equal(activityGroups([parent,child]).length,1);assert.deepEqual(scopeActivity([parent,child,orphan],{runId:'run',contextId:'A'}).map(task=>task.id),['parent']);assert.equal(scopeActivity([parent],{runId:null}).length,0);assert.equal(scopeActivity([parent],{contextId:''}).length,0);assert.equal(scopeActivity([orphan],{runId:'run'}).length,0);});
