import {useEffect,useRef,useState} from 'react';
import {Activity,ArrowDown,BrainCircuit,Check,CircleAlert,Clock3,Cpu,FileSearch,Terminal} from 'lucide-react';
import type {ActivityTask} from '../types';
import {formatActivityText} from '../format';
import {isActiveTask,isExecutingTask} from '../activity-model';

// The three observed operation steps retain the original vector identities.
// Other steps keep this implementation's existing FileSearch fallback.
export function ActivityOperationIcon({step,size}:{step?:string;size:number}) {
 const Icon=step==='context'?BrainCircuit:step==='review'?Cpu:FileSearch;
 return <Icon size={size} strokeWidth={1.6}/>;
}

export default function ActivityTaskDetail({task,waitingTask,live,frozenAt,now}:{task:ActivityTask;waitingTask?:ActivityTask;live:boolean;frozenAt:number;now:number}){
 const [outputOnly,setOutputOnly]=useState(false),[following,setFollowing]=useState(true),feed=useRef<HTMLDivElement>(null);
 const active=isActiveTask(task),executing=isExecutingTask(task),operation=task.currentOperation,events=outputOnly?task.events.filter(event=>event.log&&event.channel!=='status'):task.events;
 const logCount=task.events.filter(event=>event.log&&event.channel!=='status').length;
 const useful=task.events.filter(event=>!event.log||event.channel==='stdout'||event.channel==='stderr');
 const lastUseful=useful.reduce((last,event)=>Math.max(last,Date.parse(event.time)||0),Date.parse(task.startedAt)||0),quiet=executing&&live&&now-lastUseful>3000,unknown=active&&!live,waiting=!!task.waitingForTaskId||quiet;
 const start=active?Date.parse(operation?.startedAt||[...task.events].reverse().find(event=>!event.log&&event.status==='running')?.time||task.startedAt):Date.parse(task.startedAt),end=active?(live?now:frozenAt||now):Date.parse(task.updatedAt);
 const seconds=Math.max(0,Math.floor(((Number.isFinite(end)?end:now)-(Number.isFinite(start)?start:now))/1000)),clock=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');
 const waitingLabel=task.waitingForTaskId?(waitingTask?.runtime==='gemini'?'LLM 응답 대기':waitingTask?.runtime==='e2b'?'샌드박스 조회 결과 대기':'연결된 작업의 결과 대기'):task.runtime==='gemini'?'LLM 응답 기다리는 중':'새 출력 기다리는 중';
 useEffect(()=>{if(following&&feed.current)feed.current.scrollTop=feed.current.scrollHeight;},[task.events,outputOnly,following]);
 return <section className={`sandbox-workroom-detail is-${unknown?'connection-unknown':waiting?'waiting':task.status}`} aria-label={`${formatActivityText(task.title)} 현재 작업`}><header className="sandbox-workroom-operation"><span className="sandbox-workroom-operation-icon">{waiting||unknown?<Clock3 size={27}/>:<ActivityOperationIcon step={operation?.step||task.phase} size={27}/>}<i/></span><div><span className="sandbox-workroom-operation-caption">{unknown?'마지막으로 확인한 작업':active?'지금 하는 일':'작업 기록'}</span><strong>{formatActivityText(operation?.title||task.title)}</strong></div><span className="sandbox-workroom-elapsed"><Clock3 size={12}/><time>{clock}</time></span></header>{(operation?.detail||task.detail)&&<p className="sandbox-workroom-operation-detail">{operation?.detail||task.detail}</p>}{task.attempt&&<div className="sandbox-dock-quality"><span>검증 {task.attempt} / {task.maxAttempts||task.attempt}</span></div>}<div className="sandbox-workroom-feed-head"><span><Activity size={12}/>실시간 흐름 <b>{events.length}</b></span>{logCount>0&&<button type="button" aria-pressed={outputOnly} onClick={()=>setOutputOnly(!outputOnly)}><Terminal size={12}/>출력만</button>}<span className={`sandbox-workroom-pulse${executing&&live?' is-running':''}`} aria-label={waiting?waitingLabel:executing&&live?'실제 작업 실행 중':'작업 기록'}><i/><i/><i/><i/><i/></span></div><div className="sandbox-workroom-feed" aria-label="실제 작업과 실행 출력" ref={feed} onScroll={()=>{const element=feed.current;if(element)setFollowing(element.scrollHeight-element.scrollTop-element.clientHeight<28);}}><ol>{events.map((event,index)=><li key={event.id||index} className={`is-${event.status}${event.log&&event.channel!=='status'?' is-output':''}${event.channel==='status'?' is-heartbeat':''}${event.channel==='stderr'?' is-stderr':''}`}><span className="sandbox-workroom-event-icon">{event.channel==='status'?<Clock3 size={11}/>:event.log?<Terminal size={11}/>:event.status==='completed'?<Check size={12}/>:event.status==='failed'?<CircleAlert size={12}/>:<ActivityOperationIcon step={event.step||task.phase} size={12}/>}</span><div>{event.log?<strong className="sandbox-workroom-event-kind">{event.title}</strong>:<strong>{formatActivityText(event.title)}</strong>}{event.detail&&<p>{event.detail}</p>}</div><time>{new Date(event.time).toLocaleTimeString('ko-KR',{hour12:false})}</time></li>)}</ol>{!events.length&&<span className="sandbox-workroom-empty">{outputOnly?'수신한 실행 출력이 없습니다.':'실제 수행한 작업이 도착하면 표시됩니다.'}</span>}</div><div className="sandbox-workroom-feed-status">{unknown?<span className="sandbox-workroom-connection-note"><Clock3 size={11}/>연결 확인 중 · 마지막 수신 자료</span>:waiting?<span className="sandbox-workroom-wait"><i/><span>{waitingLabel}</span></span>:<span>{active?'실행 내용 수신 중':'수신한 작업 기록'}</span>}{!following&&<button type="button" onClick={()=>setFollowing(true)}>최신 내용<ArrowDown size={11}/></button>}</div></section>;
}
