import {lazy,memo,Suspense,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {motion} from 'motion/react';
import {LayoutDashboard,X,Sparkles,Download,ChevronRight,SlidersHorizontal,Check,Monitor,ChevronDown,Square,Terminal} from 'lucide-react';
import type {Doc,Item,ReviewRun,DashboardSourceItem} from '../types';
import {useMotionPreference} from '../motion-preference';
import type {SourceSnapshot} from './DashboardEvidence';
import SandboxActivityDock from './SandboxActivityDock';
import '../visual-contract/src/components/dashboard-modal.css';
type DashboardDesign={title:string;subtitle:string;accent:string;focus:'overview'|'exceptions'|'documents';density:'comfortable'|'compact';layout:'balanced'|'files-first'|'findings-first'|'charts-first';distribution:'doughnut'|'pie'|'bar'|'polarArea';theme:'dark'|'light';emphasis:'balanced'|'charts'|'findings';chartSize:'standard'|'large';legend:'right'|'bottom'|'hidden';motion:'full'|'subtle'|'none';corners:'rounded'|'square';fileVisualization:'cards'|'bars'};
type DashboardJob={id:string;status:'queued'|'generating'|'building'|'repairing'|'ready'|'failed';message:string;attempt:number;criterionVersion:number;logs:{id:string;time:string;step:string;status:string;title:string;detail?:string;output?:string}[];sourceItems?:DashboardSourceItem[];presentation?:'generated'|'standard';design?:DashboardDesign;html?:string;error?:string};
const DashboardEvidence=lazy(()=>import('./DashboardEvidence'));
type Props={open:boolean;onClose:()=>void;run:ReviewRun|null;context?:{e2bConfigured?:boolean;documents?:Doc[]}};
type Preview={job:DashboardJob;sourceSnapshot:SourceSnapshot|null;token:string};
const cache:Map<string,Preview>=import.meta.hot?.data.dashboardPreviews??new Map<string,Preview>();
import.meta.hot?.dispose(data=>{data.dashboardPreviews=cache;});
const defaultInstruction='라이트 테마에 도넛 차트를 크게 배치하고 차트를 강조해 주세요. 파일별 결과를 비교하고, 파일을 선택하면 항목·측정값·기준·판정과 확인이 필요한 이유를 볼 수 있게 해 주세요.';
const suggestions=[['라이트 · 큰 도넛',defaultInstruction],['다크 · 차트 중심','다크 테마에 파란색을 포인트로 쓰고, 차트를 맨 위에 크게 배치해 강조해 주세요. 전체 판정은 막대 차트로 보여 주고 범례는 아래에 놓아 주세요. 파일을 선택하면 판정 근거를 확인할 수 있게 해 주세요.'],['촘촘한 파일 비교','라이트 테마에 촘촘한 구성으로 파일별 비교를 맨 위에 보여 주세요. 파일별 결과는 막대로 비교하고, 전체 판정은 파이 차트로 정리해 주세요. 모서리는 각지게 하고 애니메이션은 없애 주세요.'],['확인할 항목 먼저','부적합과 확인이 필요한 검토 항목을 가장 먼저 배치하고 강조해 주세요. 따뜻한 주황색을 포인트로 쓰고, 전체 판정은 도넛 차트로 정리해 주세요. 어떤 항목을 왜 확인해야 하는지 쉽게 펼쳐볼 수 있게 해 주세요.']];
function freeze<T>(value:T):T{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(freeze);}return value;}
export function designTags(design:DashboardDesign){const emphasis=design.emphasis==='charts'?'차트 강조':design.emphasis==='findings'?'검토 항목 강조':({'balanced':'균형 구성','files-first':'파일 먼저','findings-first':'검토 항목 먼저','charts-first':'차트 먼저'}[design.layout]);const detail=design.chartSize==='large'?'큰 차트':design.fileVisualization==='bars'?'파일 막대 비교':design.motion==='none'?'애니메이션 없음':design.legend==='hidden'?'범례 숨김':design.legend==='bottom'?'아래쪽 범례':design.corners==='square'?'각진 모서리':design.motion==='subtle'?'잔잔한 움직임':'';return [design.theme==='light'?'라이트':'다크',({doughnut:'도넛',pie:'파이',bar:'막대',polarArea:'극좌표'}[design.distribution]),emphasis,detail].filter(Boolean);}
export function dashboardMotionHtml(html:string,enabled:boolean){return enabled?html:html.replace('</head>','<meta name="trace-reduced-motion" content="true"><style>*,*::before,*::after{animation:none!important;transition:none!important}</style></head>');}
export function dashboardBridge(html:string,token:string,ids:string[],origin:string){const nonce=/<script\b[^>]*\bnonce="([^"]+)"/.exec(html)?.[1];if(!nonce||!html.includes(`script-src 'nonce-${nonce}'`)||!/^https?:\/\/[^/]+$/.test(origin))return html;const encoded=(v:unknown)=>JSON.stringify(v).replace(/</g,'\\u003c');const script=`(()=>{const token=${encoded(token)},known=new Set(${encoded(ids.filter(id=>id.length>=1&&id.length<=200))}),origin=${encoded(origin)};document.documentElement.dataset.traceSourceAvailable='true';function send(event){if(!event.isTrusted)return;if(event.type==='keydown'&&!['Enter',' '].includes(event.key))return;const target=event.target?.closest?.('[data-review-source]');if(!target||!known.has(target.dataset.reviewSource))return;parent.postMessage({channel:'trace-dashboard-evidence-v1',type:'select-item',token,itemId:target.dataset.reviewSource},origin);}document.addEventListener('click',send);document.addEventListener('keydown',send);})();`;return html.replace('</body>',`<script nonce="${nonce}">${script}</script></body>`);}
const ChartPreview=memo(function ChartPreview({html,frameRef}:{html:string;frameRef:React.RefObject<HTMLIFrameElement|null>}){return <iframe ref={frameRef} className="dashboard-preview-frame" title="나만의 대시보드" sandbox="allow-scripts" referrerPolicy="no-referrer" srcDoc={html}/>;});
const dashboardSandboxSteps=[
 {label:'파일 준비',steps:['prepare','files']},
 {label:'검증 환경 준비',steps:['install']},
 {label:'차트 구성',steps:['build']},
 {label:'실데이터 검사',steps:['validate']},
 {label:'수정 · 종료',steps:['repair','cleanup']},
];
const dashboardLogStatus=(status:string)=>(({running:'실행 중',completed:'완료',failed:'실패',info:'기록',waiting:'대기'} as Record<string,string>)[status]||'대기');
function DashboardActivity({job,busy,open,onToggle,reduceMotion}:{job:DashboardJob;busy:boolean;open:boolean;onToggle:()=>void;reduceMotion:boolean}){
 const terminal=useRef<HTMLDivElement>(null),follow=useRef(true),logs=job.logs||[],latestEvent=[...logs].reverse().find(entry=>entry.status!=='info'),running=busy&&latestEvent?.status==='running',completed=job.status==='ready';
 useEffect(()=>{if(open&&follow.current&&terminal.current)terminal.current.scrollTop=terminal.current.scrollHeight;},[logs,open]);
 return <section className={`dashboard-activity${open?' is-open':''}${completed?' is-complete':''}`} aria-label="샌드박스 작업 기록"><button type="button" className="dashboard-activity-toggle" onClick={onToggle} aria-expanded={open} aria-controls="dashboard-sandbox-log"><motion.span className={`dashboard-activity-computer${running?' is-running':''}`} animate={running&&!reduceMotion?{opacity:[1,.5,1]}:{opacity:1}} transition={{repeat:running&&!reduceMotion?Infinity:0,duration:1.7,ease:'easeInOut'}}><Monitor size={15} strokeWidth={1.7}/></motion.span><span className="dashboard-activity-heading">작업 과정 보기</span><span className="dashboard-activity-count">{logs.length}</span><span className="dashboard-activity-summary">{completed?'실행 완료':latestEvent?.title||'실행 대기'}</span><ChevronDown size={14} className="dashboard-activity-chevron"/></button>{open&&<div id="dashboard-sandbox-log" className="dashboard-activity-content"><ol className="dashboard-sandbox-steps" aria-label="샌드박스 실행 단계">{dashboardSandboxSteps.map(({label,steps},index)=>{const event=[...logs].reverse().find(entry=>steps.includes(entry.step)&&entry.status!=='info'),status=event?.status||'waiting';return <li key={label} className={`is-${status}`} aria-current={busy&&status==='running'?'step':undefined}><span className="dashboard-sandbox-step-icon" aria-hidden="true">{status==='completed'?<Check size={10}/>:status==='failed'?<X size={10}/>:index+1}</span><span className="dashboard-sandbox-step-label">{label}<small>{dashboardLogStatus(status)}</small></span></li>;})}</ol><div ref={terminal} className="dashboard-terminal" role="region" aria-label="실제 샌드박스 실행 로그" tabIndex={0} onScroll={()=>{if(terminal.current)follow.current=terminal.current.scrollHeight-terminal.current.scrollTop-terminal.current.clientHeight<36;}}>{logs.length?<ol className="dashboard-log-entries">{logs.map(entry=><li key={entry.id} className={`dashboard-log-entry is-${entry.status}`}><div className="dashboard-log-line"><time>{Number.isFinite(Date.parse(entry.time))?new Date(entry.time).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):''}</time><span className="dashboard-log-status">{dashboardLogStatus(entry.status)}</span><strong>{entry.title}</strong></div>{entry.detail&&<p className="dashboard-log-detail">{entry.detail}</p>}{entry.output&&<pre className="dashboard-log-output">{entry.output}</pre>}</li>)}</ol>:<div className="dashboard-log-empty"><Terminal size={14}/><span>실제 실행 기록을 기다리고 있습니다.</span></div>}</div></div>}</section>;
}
export default function DashboardModal({open,onClose,run,context}:Props){
 const {enabled}=useMotionPreference(),dialog=useRef<HTMLDialogElement>(null),frame=useRef<HTMLIFrameElement>(null),sequence=useRef(0),alive=useRef(true),busyRef=useRef(false),pollTimer=useRef<ReturnType<typeof setTimeout>|null>(null),getAbort=useRef<AbortController|null>(null),activeJob=useRef<string|null>(null);
 const [instruction,setInstruction]=useState(defaultInstruction),[preview,setPreview]=useState<Preview|null>(()=>run?cache.get(run.id)||null:null),[job,setJob]=useState<DashboardJob|null>(null),[busy,setBusy]=useState(false),[activityStartedAfter,setActivityStartedAfter]=useState<number>(),[builder,setBuilder]=useState(()=>!run||!cache.has(run.id)),[logs,setLogs]=useState(false),[contentReady,setContentReady]=useState(false),[view,setView]=useState<'charts'|'source'>('charts'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selectedSourceId,setSelectedSourceId]=useState<string|null>(null),[selectionVersion,setSelectionVersion]=useState(0),[mountedChartId,setMountedChartId]=useState<string|null>(null);
 const discard=(id:string)=>{void fetch(`/api/dashboards/${encodeURIComponent(id)}`,{method:'DELETE'}).catch(()=>{});};
 const cancel=useCallback((showNotice=true)=>{sequence.current++;getAbort.current?.abort();if(pollTimer.current)clearTimeout(pollTimer.current);pollTimer.current=null;if(activeJob.current)discard(activeJob.current);activeJob.current=null;busyRef.current=false;setBusy(false);setError('');if(showNotice)setNotice('생성을 취소했어요. 원하는 구성을 적고 다시 시작할 수 있어요.');},[]);
 const close=()=>{cancel(false);dialog.current?.close();onClose();};
 useEffect(()=>{alive.current=true;if(open){dialog.current?.showModal();setContentReady(false);setView('charts');setMountedChartId(null);const saved=run?cache.get(run.id):undefined;setPreview(saved||null);setBuilder(!saved);setSelectedSourceId(null);const timer=setTimeout(()=>setContentReady(true),260);return()=>{alive.current=false;clearTimeout(timer);cancel(false);dialog.current?.close();};}return()=>{alive.current=false;cancel(false);};},[open,run?.id,cancel]);
 const motionHtml=useMemo(()=>contentReady&&preview?.job.html?dashboardMotionHtml(preview.job.html,enabled):'',[preview,enabled,contentReady]);
 const iframeHtml=useMemo(()=>preview?.sourceSnapshot?dashboardBridge(motionHtml,preview.token,preview.sourceSnapshot.items.map(i=>i.id),window.location.origin):motionHtml,[preview,motionHtml]);
 const selectSource=useCallback((id:string)=>{setSelectedSourceId(id);setSelectionVersion(v=>v+1);setView('source');requestAnimationFrame(()=>dialog.current?.querySelector<HTMLElement>('.dbe-inspector')?.focus());},[]);
 useEffect(()=>{if(!preview?.sourceSnapshot)return;const known=new Set(preview.sourceSnapshot.items.map(i=>i.id));const listener=(event:MessageEvent)=>{const data=event.data;if(event.source!==frame.current?.contentWindow||event.origin!=='null'||!data||data.channel!=='trace-dashboard-evidence-v1'||data.type!=='select-item'||data.token!==preview.token||!known.has(data.itemId))return;selectSource(data.itemId);};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener);},[preview,selectSource]);
 useEffect(()=>{if(contentReady&&preview&&view==='charts'&&!busy)setMountedChartId(preview.job.id);},[contentReady,preview,view,busy]);

 async function generate(){if(!run||busyRef.current||!instruction.trim())return;busyRef.current=true;const id=++sequence.current,documents=freeze(structuredClone(context?.documents||[...run.documents,...(run.criteriaDocuments||[])]));setBusy(true);setJob(null);setError('');setNotice('');setBuilder(true);setLogs(true);setMountedChartId(null);getAbort.current?.abort();const current=()=>alive.current&&sequence.current===id;const stop=(message:string)=>{if(!current())return;busyRef.current=false;setBusy(false);setError(message);};let errors=0;const poll=async(jobId:string)=>{if(!current())return;const abort=new AbortController();getAbort.current=abort;try{const response=await fetch(`/api/dashboards/${encodeURIComponent(jobId)}`,{signal:abort.signal,cache:'no-store'});if(!response.ok)throw new Error('대시보드 진행 상태를 확인하지 못했어요. 다시 시도해 주세요.');const next:DashboardJob=await response.json();if(!current())return;errors=0;setJob(next);if(next.status==='ready'){activeJob.current=null;busyRef.current=false;setBusy(false);if(!next.html?.trim()){setError('생성된 화면이 비어 있어요. 다시 구성해 주세요.');return;}const created={job:next,sourceSnapshot:next.sourceItems?freeze({documents,items:next.sourceItems as Item[]}):null,token:crypto.randomUUID()};cache.delete(run.id);cache.set(run.id,created);if(cache.size>5)cache.delete(cache.keys().next().value!);setPreview(created);setSelectedSourceId(null);setView('charts');setBuilder(false);setLogs(false);return;}if(next.status==='failed'){activeJob.current=null;stop(next.error||next.message||'대시보드를 만들지 못했어요. 다시 구성해 주세요.');return;}pollTimer.current=setTimeout(()=>void poll(jobId),1200);}catch(error){if(!current()||abort.signal.aborted)return;if(++errors<3){pollTimer.current=setTimeout(()=>void poll(jobId),1200);return;}discard(jobId);activeJob.current=null;stop(error instanceof Error?error.message:'대시보드 진행 상태를 확인하지 못했어요.');}};
 try{setActivityStartedAfter(Date.now());const response=await fetch('/api/dashboards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({runId:run.id,instruction:instruction.trim().slice(0,1500),...(preview?.job.design?{baseDesign:preview.job.design}:{})})});const next=await response.json();if(!current()){if(next.id)discard(next.id);return;}if(!response.ok)throw new Error(next.error||'대시보드를 만들지 못했어요. 다시 구성해 주세요.');setJob(next);activeJob.current=next.id;void poll(next.id);}catch(error){stop(error instanceof Error?error.message:'대시보드를 만들지 못했어요.');}}
 const download=()=>{if(!motionHtml||!run)return;const url=URL.createObjectURL(new Blob([motionHtml],{type:'text/html;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`gspec-dashboard-${run.id.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,16)}.html`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 if(!open||!run)return null;
 return <dialog ref={dialog} className="dashboard-modal" aria-labelledby="dashboard-title" aria-describedby="dashboard-description" onCancel={event=>{event.preventDefault();close();}}><motion.div className="dashboard-shell" initial={enabled?{opacity:0,y:14,scale:.985}:false} animate={{opacity:1,y:0,scale:1}} transition={{duration:.24,ease:'easeOut'}}><header className="dashboard-header"><div className="dashboard-header-brand"><span className="dashboard-brand-icon"><LayoutDashboard size={21}/></span><div><div className="dashboard-eyebrow">A DIFFERENT PERSPECTIVE</div><h2 id="dashboard-title">나만의 대시보드</h2></div></div><div className="dashboard-header-actions">{preview&&!busy&&<button className="dashboard-config-toggle" aria-expanded={builder} onClick={()=>setBuilder(!builder)}><SlidersHorizontal size={14}/>{builder?'구성 접기':'구성 수정'}</button>}<button type="button" className="dashboard-icon-button" aria-label="대시보드 닫기" onClick={close}><X size={20}/></button></div></header><div className={`dashboard-body${busy?' is-generating':!builder?' is-preview-focused':''}`}>
 {builder&&!busy&&<aside id="dashboard-builder-panel" className="dashboard-sidebar"><div className="dashboard-sidebar-intro"><span className="dashboard-small-label"><Sparkles size={12}/> YOUR VIEW</span><h3>중요한 것부터,<br/>당신의 방식으로.</h3><p id="dashboard-description">테마, 차트 종류와 크기, 보여줄 순서를 자유롭게 조합해 주세요.</p></div><label className="dashboard-input-label" htmlFor="dashboard-instruction">어떤 화면이 필요하세요?</label><textarea id="dashboard-instruction" className="dashboard-instruction" maxLength={1500} value={instruction} disabled={busy} onChange={event=>setInstruction(event.target.value)}/><div className="dashboard-suggestions" aria-label="구성 제안">{suggestions.map(([label,value])=><button type="button" key={label} className={`dashboard-suggestion${instruction===value?' dashboard-suggestion-selected':''}`} disabled={busy} onClick={()=>setInstruction(value)}>{label}</button>)}</div><button type="button" className="button primary dashboard-generate" disabled={busy||!instruction.trim()} onClick={generate}><Sparkles size={16}/>{preview?'다시 구성':'대시보드 만들기'}<ChevronRight className="dashboard-button-arrow" size={16}/></button><div className="dashboard-feedback" aria-live="polite" aria-atomic="true">{error&&<p role="alert" className="dashboard-error">{error}</p>}{notice&&<p>{notice}</p>}</div><div className="dashboard-snapshot-note"><span className="dashboard-note-mark"><Check size={14}/></span><p>생성 요청 시점의 검토 데이터를 담아요. 검토 내용이 바뀌면 다시 구성해 주세요.</p></div></aside>}
 <section className={"dashboard-preview-section"+(busy?" is-generating":"")} aria-label="생성된 대시보드 미리보기">
 <div className="dashboard-preview-toolbar">{busy?<div className="dashboard-generation-status" role="status"><Sparkles size={15}/><div><strong>LLM과 샌드박스가 화면을 만드는 중</strong><small>{job?.message||'검토 결과에 맞는 화면을 구성하고 있어요'}</small></div></div>:<div className="dashboard-preview-label"><span className={`dashboard-preview-dot${preview?' is-ready':''}`}/>{preview?`${preview.job.presentation==='standard'?'기본 자동 시각화':'나만의 대시보드'} · 기준 v${preview.job.criterionVersion}`:'미리보기'}</div>}{preview&&!busy&&<div className="dashboard-view-switch" role="group" aria-label="대시보드 보기"><button type="button" className={view==='source'?'is-active':''} disabled={!preview.sourceSnapshot} aria-pressed={view==='source'} title={preview.sourceSnapshot?'실제 원본과 판정 근거 보기':'원본과 판정을 보려면 다시 구성해 주세요.'} onClick={()=>setView('source')}>원본과 판정</button><button type="button" className={view==='charts'?'is-active':''} aria-pressed={view==='charts'} onClick={()=>setView('charts')}>대시보드</button></div>}{busy?<div className="dashboard-generation-actions"><button type="button" className="dashboard-cancel" onClick={()=>cancel()}><Square size={10} fill="currentColor"/>생성 취소</button></div>:<div className="dashboard-preview-actions"><button type="button" className="dashboard-download" disabled={!preview||!contentReady} onClick={download}><Download size={14}/><span>시각화 HTML</span></button></div>}</div>
 {preview?.job.presentation!=='standard'&&preview?.job.design&&!busy&&view==='charts'&&<div className="dashboard-design-summary" aria-label="실제로 적용된 디자인"><span>적용된 디자인</span><ul>{designTags(preview.job.design).map(tag=><li key={tag}>{tag}</li>)}</ul></div>}
 {busy&&<div className="dashboard-build-activity"><SandboxActivityDock runId={run.id} contextId={job?.id??null} startedAfter={activityStartedAfter} taskKinds={['dashboard']} busy title="대시보드 만드는 과정" defaultExpanded/></div>}
 <div className="dashboard-preview-canvas" aria-busy={busy} hidden={busy}>{!busy&&(preview&&contentReady?<>{view==='source'&&preview.sourceSnapshot&&<div className="dashboard-source-view" tabIndex={-1} aria-label="선택한 항목의 원본과 판정"><Suspense fallback={<div className="dashboard-preview-loading" role="status"><LayoutDashboard size={25} strokeWidth={1.4}/><span>원본과 판정을 불러오는 중</span><i aria-hidden="true"/></div>}><DashboardEvidence snapshot={preview.sourceSnapshot} selectedId={selectedSourceId} selectionVersion={selectionVersion} onSelect={selectSource}/></Suspense></div>}{(view==='charts'||mountedChartId===preview.job.id)&&<div className="dashboard-chart-view" hidden={view!=='charts'}>{preview.job.presentation==='standard'&&<div className="dashboard-source-legacy">요청한 디자인을 완성하지 못해 기본 차트를 보여드려요. 일부 디자인 요청은 적용되지 않았어요.</div>}<ChartPreview html={iframeHtml} frameRef={frame}/></div>}</>:<div className="dashboard-empty"><div className="dashboard-empty-art" aria-hidden="true"><div className="dashboard-art-orbit dashboard-art-orbit-one"/><div className="dashboard-art-orbit dashboard-art-orbit-two"/><div className="dashboard-art-card"><div className="dashboard-art-card-header"><i/><i/><i/></div><div className="dashboard-art-metrics"><i/><i/><i/></div><div className="dashboard-art-chart"/><div className="dashboard-art-lines"><i/><i/><i/></div></div><div className="dashboard-art-badge"><Sparkles size={18}/></div></div><span className="dashboard-empty-eyebrow">YOUR RESULTS, REIMAGINED</span><h3>검토 결과에 새로운 관점을</h3><p>원하는 구성을 적고 대시보드를 만들어 보세요.</p></div>)}</div>
 {!busy&&job&&<DashboardActivity job={job} busy={false} open={logs} onToggle={()=>setLogs(!logs)} reduceMotion={!enabled}/>}</section></div></motion.div></dialog>;
}
