import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {motion,useReducedMotion} from 'motion/react';
import {FileText,FileSearch,Check,X,HelpCircle,ChevronDown,MousePointer2,ScanSearch,ArrowUpRight} from 'lucide-react';
import {PieChart,Pie,Cell} from 'recharts';
import type {Doc,Item} from '../types';
import {useMotionPreference} from '../motion-preference';
import {formatValue} from '../format';
import '../visual-contract/src/components/dashboard-evidence.css';
export type SourceSnapshot={documents:Doc[];items:Item[]};
const DocumentPreview=lazy(()=>import('./DocumentPreview'));
const statusLabels={pass:'적합',fail:'부적합',review:'확인 필요',pending:'미완료'};
const statusColors={pass:'#70f3c4',fail:'#ff8f91',review:'#ffd080',pending:'#a0abc1'};
export default function DashboardEvidence({snapshot,selectedId,selectionVersion,onSelect}:{snapshot:SourceSnapshot;selectedId:string|null;selectionVersion:number;onSelect:(id:string)=>void}){
 const inspector=useRef<HTMLElement>(null);
 useEffect(()=>{if(selectedId&&snapshot.items.some(item=>item.id===selectedId))inspector.current?.focus();},[selectedId,selectionVersion,snapshot.items]);
 const {enabled}=useMotionPreference(),osReduced=useReducedMotion(),reduceSourceMotion=!enabled||Boolean(osReduced);
 const statuses=['pass','fail','review'] as const,viewStatus=(status:Item['status'])=>status==='pending'?'review':status;const enter=(delay=0)=>({initial:reduceSourceMotion?false as const:{opacity:0,y:6},animate:{opacity:1,y:0},transition:{duration:reduceSourceMotion?0:.32,delay:reduceSourceMotion?0:delay,ease:[.22,1,.36,1] as const}});
 const {documents,items}=snapshot;const reviewed=useMemo(()=>{const ids=[...new Set([...documents.filter(d=>d.role==='target').map(d=>d.id),...items.map(i=>i.documentId)])];return ids.map(id=>documents.find(d=>d.id===id)||({id,name:'문서 정보 없음',role:'target'} as Doc));},[documents,items]);const [reviewId,setReviewId]=useState(reviewed[0]?.id||''),[sourceId,setSourceId]=useState<string|null>(documents.some(d=>d.id===reviewed[0]?.id)?reviewed[0]?.id:null),[filter,setFilter]=useState('all'),[referenceIndex,setReferenceIndex]=useState<number|null>(null);const selected=items.find(i=>i.id===selectedId&&i.documentId===reviewId),source=documents.find(d=>d.id===sourceId),fileItems=items.filter(i=>i.documentId===reviewId),visible=fileItems.filter(i=>filter==='all'||viewStatus(i.status)===filter),evidence=selected?.evidence||[];const sourceDocumentIds=new Set([...reviewed.map(d=>d.id),...items.flatMap(item=>(item.evidence||[]).map(reference=>reference.documentId))]),relevantDocuments=documents.filter(document=>sourceDocumentIds.has(document.id));
 const selectFile=(id:string)=>{setReviewId(id);setSourceId(documents.some(d=>d.id===id)?id:null);setReferenceIndex(null);setFilter('all');};
 useEffect(()=>{const item=items.find(i=>i.id===selectedId);if(!item)return;setReviewId(item.documentId);const known=(id:string)=>documents.some(d=>d.id===id);const references=item.evidence||[];let index=references.findIndex(e=>e.documentId===item.documentId&&known(e.documentId));if(index<0)index=references.findIndex(e=>documents.some(d=>d.id===e.documentId&&d.role==='target'));if(index<0)index=references.findIndex(e=>known(e.documentId));setReferenceIndex(index>=0?index:references.length?0:null);setSourceId(index>=0?references[index].documentId:known(item.documentId)?item.documentId:null);setFilter(prior=>prior!=='all'&&prior!==viewStatus(item.status)?'all':prior);},[selectedId,selectionVersion,items,documents]);
 const changeSource=(id:string)=>{if(reviewed.some(d=>d.id===id)&&id!==reviewId){selectFile(id);return;}setSourceId(id);const index=evidence.findIndex(e=>e.documentId===id);setReferenceIndex(index<0?null:index);};
 const counts=statuses.map(status=>({status,value:fileItems.filter(item=>viewStatus(item.status)===status).length})),slices=counts.filter(count=>count.value>0);const currentEvidence=referenceIndex===null?undefined:evidence[referenceIndex],pendingCount=fileItems.filter(item=>item.status==='pending').length;
 return <section className="dashboard-evidence" data-reduced-motion={reduceSourceMotion||undefined} aria-label="파일별 원문과 판정 연결 보기" data-review-document-id={reviewId||undefined} data-source-document-id={sourceId||undefined} data-selected-item-id={selected?.id} data-status-filter={filter} data-selected-evidence-index={referenceIndex??undefined}>
 <div className="dbe-file-tabs" role="group" aria-label="검토 파일 선택">{reviewed.map(document=><button type="button" key={document.id} className="dbe-file-tab" data-review-file-id={document.id} title={document.name} aria-pressed={document.id===reviewId} onClick={()=>selectFile(document.id)}><FileText size={15}/><span className="dbe-file-name">{document.name}</span><span className="dbe-file-counts">{statuses.map(status=>{const count=items.filter(item=>item.documentId===document.id&&viewStatus(item.status)===status).length;return <span className={'is-'+status} key={status} aria-label={`${statusLabels[status]} ${count}개`} title={statusLabels[status]}>{count}</span>;})}</span></button>)}</div>
 <motion.header className="dbe-overview" {...enter()}><div className="dbe-overview-title"><FileSearch size={17}/><span>이 파일의 판정</span></div><button type="button" className={'dbe-total'+(filter==='all'?' is-active':'')} aria-pressed={filter==='all'} aria-label={`이 파일의 전체 ${fileItems.length}개 항목 표시`} onClick={()=>setFilter('all')}><span className="dbe-mini-donut" aria-hidden="true"><PieChart width={48} height={48}><Pie data={slices.length?slices:[{status:'empty',value:1}]} dataKey="value" cx="50%" cy="50%" innerRadius={14} outerRadius={21} startAngle={90} endAngle={-270} paddingAngle={slices.length>1?3:0} cornerRadius={2} stroke="none" isAnimationActive={!reduceSourceMotion&&fileItems.length>0} animationDuration={700} animationEasing="ease-out">{(slices.length?slices:[{status:'empty',value:1}]).map(slice=><Cell key={slice.status} fill={statusColors[slice.status as keyof typeof statusColors]||'#343d4d'} opacity={filter==='all'||filter===slice.status?1:.25}/>)}</Pie></PieChart></span><span>전체 <strong>{fileItems.length}</strong></span></button><div className="dbe-status-filters" aria-label="판정별 필터">{counts.map(count=><button type="button" key={count.status} className={'dbe-status-filter'+(filter===count.status?' is-active':'')} style={{'--dbe-status':statusColors[count.status]} as React.CSSProperties} aria-pressed={filter===count.status} title={count.status==='review'&&pendingCount?`미완료 ${pendingCount}개 포함`:undefined} onClick={()=>setFilter(filter===count.status?'all':count.status)}>{count.status==='pass'?<Check size={13}/>:count.status==='fail'?<X size={13}/>:<HelpCircle size={13}/>}<span>{statusLabels[count.status]}</span><strong>{count.value}</strong></button>)}</div></motion.header>
 <div className="dbe-body"><motion.section className="dbe-source" aria-label="원본 문서" {...enter(.05)}><header className="dbe-source-heading"><FileText size={14}/><label className="dbe-document-picker"><span className="dbe-sr-only">원본 문서 선택</span><select disabled={!relevantDocuments.length} value={sourceId||''} onChange={event=>changeSource(event.target.value)}>{!sourceId&&<option value="">원본 문서 선택</option>}{relevantDocuments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><ChevronDown size={12}/></label><span className="dbe-source-count">모든 판정 표시</span></header><div className="dbe-source-preview">{source?<Suspense fallback={<div>원본을 준비하고 있어요.</div>}><DocumentPreview document={source} stage="complete" items={items} evidence={currentEvidence?[currentEvidence]:[]} selectedItemId={selected?.id||null} onSelectItem={onSelect} compact/></Suspense>:<div>연결된 원본 문서를 찾을 수 없습니다.</div>}</div></motion.section>
 <aside className="dbe-results" aria-label="항목과 선택 근거"><motion.section className="dbe-map-panel" aria-label="항목별 판정 지도" {...enter(.09)}><header className="dbe-panel-heading"><h3>이 파일의 항목</h3><span>{visible.length} / {fileItems.length}<MousePointer2 size={11}/></span></header><div className="dbe-item-map">{visible.map((item,index)=><motion.button type="button" initial={reduceSourceMotion?false:{opacity:0,scale:.75}} animate={{opacity:1,scale:1}} transition={{duration:reduceSourceMotion?0:.22,ease:[.22,1,.36,1],delay:reduceSourceMotion?0:Math.min(index,20)*.008}} whileHover={reduceSourceMotion?undefined:{y:-2}} whileTap={reduceSourceMotion?undefined:{scale:.92}} key={item.id} className={'dbe-item-mark'+(selected?.id===item.id?' is-selected':'')} data-item-id={item.id} data-item-status={item.status} style={{'--dbe-status':statusColors[viewStatus(item.status)]} as React.CSSProperties} aria-label={String(fileItems.indexOf(item)+1)+'. '+item.label+', '+formatValue(item.value)+' '+(item.unit||'')+', '+(item.status==='pending'?'확인 필요 · 미완료':statusLabels[viewStatus(item.status)])+'. 원문 근거 보기'} aria-pressed={selected?.id===item.id} title={String(fileItems.indexOf(item)+1)+'. '+item.label+' · '+formatValue(item.value)+' '+(item.unit||'')+' · '+(item.status==='pending'?'확인 필요 · 미완료':statusLabels[viewStatus(item.status)])} onClick={()=>onSelect(item.id)}><span>{fileItems.indexOf(item)+1}</span></motion.button>)}{!visible.length&&<p className="dbe-map-empty">해당 판정의 항목이 없습니다.</p>}</div></motion.section>
 <section ref={inspector} className="dbe-inspector" aria-label="선택한 항목의 판정과 근거" tabIndex={-1}>{selected?<motion.div key={selected.id} className="dbe-inspector-content" {...enter()}>
  <header className="dbe-inspector-header"><span className="dbe-verdict" style={{'--dbe-status':statusColors[viewStatus(selected.status)]} as React.CSSProperties}>{viewStatus(selected.status)==='pass'?<Check size={12}/>:viewStatus(selected.status)==='fail'?<X size={12}/>:<HelpCircle size={12}/>} {selected.status==='pending'?'확인 필요 · 미완료':statusLabels[viewStatus(selected.status)]}</span><h3>{selected.label}</h3><p>{reviewed.find(document=>document.id===selected.documentId)?.name||'문서 정보 없음'}</p></header>
  <div className="dbe-inspector-scroll"><div className="dbe-measurement"><span>문서에서 확인한 값</span><strong>{formatValue(selected.value)}</strong>{selected.unit&&<small>{selected.unit}</small>}</div>
   {selected.criterion&&<div className="dbe-detail-block"><h4>적용 기준</h4><p>{selected.criterion}</p></div>}
   {selected.explanation&&<div className="dbe-detail-block"><h4>판정 이유</h4><p>{selected.explanation}</p></div>}
   {selected.reviewedByHuman&&<div className="dbe-human-note"><Check size={12}/><span>사용자 확인{selected.humanNote?' · '+selected.humanNote:''}</span></div>}
   <div className="dbe-detail-block dbe-reference-block"><h4>원문 근거 <span>{evidence.length}</span></h4>{evidence.length?<><div className="dbe-references" aria-label="근거 위치 선택">{evidence.map((e,index)=>{const sourceDocument=documents.find(document=>document.id===e.documentId);return <button type="button" key={e.documentId+'-'+index} className={'dbe-reference'+(referenceIndex===index?' is-active':'')} data-evidence-document-id={e.documentId} data-evidence-page={e.page} data-evidence-sheet={e.sheet} data-evidence-cell={e.cell} aria-pressed={referenceIndex===index} onClick={()=>{setReferenceIndex(index);if(sourceDocument)setSourceId(e.documentId);}}><span>{index+1}</span><span><strong>{sourceDocument?.name||'문서 정보 없음'}</strong><small>{[e.page?String(e.page)+'쪽':'',e.sheet,e.cell].filter(Boolean).join(' · ')||'위치 정보 없음'}</small></span>{sourceDocument&&<ArrowUpRight size={12}/>}</button>;})}</div>{currentEvidence?.quote&&<blockquote className="dbe-source-quote">{currentEvidence.quote}</blockquote>}{currentEvidence&&!documents.some(document=>document.id===currentEvidence.documentId)&&<p className="dbe-unlocated">연결된 원본 문서를 찾을 수 없습니다.</p>}</>:<p className="dbe-unlocated">연결된 원문 근거가 없습니다.</p>}</div>
  </div></motion.div>:<motion.div key="empty" className="dbe-inspector-empty" {...enter()}><span className="dbe-empty-symbol"><ScanSearch size={28} strokeWidth={1.2}/><i/><i/></span><h3>색을 누르면, 근거까지.</h3><p>원문의 표시나 항목을 선택해 보세요.</p><span className="dbe-empty-statuses" aria-hidden="true">{statuses.map(status=><i key={status} style={{background:statusColors[status]}}/>)}</span></motion.div>}</section></aside></div></section>;
}
