import {useEffect,useState,type CSSProperties} from 'react';
import {createPortal} from 'react-dom';
import {animate,AnimatePresence,motion,useIsPresent,useMotionValue,useReducedMotion,useTransform} from 'motion/react';
import {ResponsiveContainer,PieChart,Pie,Cell,Tooltip,BarChart,Bar,XAxis,YAxis} from 'recharts';
import {FileCheck2,FileText,Layers3,HelpCircle,Check,ArrowUpRight,Sparkles} from 'lucide-react';
import type {Item,ReviewRun,Verdict} from '../types';
import {StatusIcon,statusLabels} from './ReviewItems';
import {formatValue} from '../format';
import {useMotionPreference} from '../motion-preference';
import '../visual-contract/src/components/results-visuals.css';
const verdicts=['pass','fail','review','pending'] as const,colors={pass:'#70f3c4',fail:'#ff8f91',review:'#ffd080',pending:'#a0abc1'},ease=[.22,1,.36,1] as const;
const shortName=(name:string,length=14)=>name.length>length?name.slice(0,length-1)+'…':name;
function Count({value,reduced}:{value:number;reduced:boolean}){const count=useMotionValue(reduced?value:0),display=useTransform(count,current=>Math.round(current).toLocaleString('ko-KR'));useEffect(()=>{if(reduced){count.set(value);return;}const animation=animate(count,value,{duration:.65,ease});return()=>animation.stop();},[count,value,reduced]);return <motion.strong key={value} initial={{opacity:reduced?1:0,y:reduced?0:7}} animate={{opacity:1,y:0}} transition={{duration:reduced?0:.28,ease}}><span className="visually-hidden">{value}</span>{reduced?<span aria-hidden="true">{value.toLocaleString('ko-KR')}</span>:<motion.span aria-hidden="true">{display}</motion.span>}</motion.strong>;}
function ResultTile({item,index,reduced,described,onSelect,onOpen,onClose}:{item:Item;index:number;reduced:boolean;described:boolean;onSelect:()=>void;onOpen:(element:HTMLElement)=>void;onClose:()=>void}){const present=useIsPresent();return <motion.button className={`rv-item-tile ${item.status}`} layout={!reduced?'position':false} style={{'--rv-color':colors[item.status],pointerEvents:present?undefined:'none'} as CSSProperties} initial={{opacity:0,scale:reduced?1:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:reduced?1:.96}} transition={{duration:reduced?0:.3,ease,delay:reduced?0:Math.min(index,8)*.022}} whileHover={reduced?undefined:{y:-2}} whileTap={reduced?undefined:{scale:.98}} disabled={!present} tabIndex={present?0:-1} aria-hidden={!present} aria-label={`${item.label}, ${formatValue(item.value)} ${item.unit||''}, ${statusLabels[item.status]}, 원문과 근거 보기`} aria-describedby={described?'rv-item-tooltip':undefined} onMouseEnter={event=>onOpen(event.currentTarget)} onFocus={event=>onOpen(event.currentTarget)} onMouseLeave={onClose} onBlur={onClose} onClick={()=>{onClose();onSelect();}}><div className="rv-tile-title"><StatusIcon status={item.status} size={13}/><span>{item.label}</span><ArrowUpRight className="rv-tile-arrow" size={11}/></div><div className="rv-tile-value"><strong>{formatValue(item.value)}</strong><small>{item.unit}</small></div><span className="rv-tile-status">{statusLabels[item.status]}{item.reviewedByHuman&&<Check size={10} aria-label="사람 확인 완료"/>}</span></motion.button>;}
export default function ResultsVisuals({run,onSelectItem,showDashboardButton=false,dashboardDisabled=false,onDashboard}:{run:ReviewRun;onSelectItem:(id:string)=>void;showDashboardButton?:boolean;dashboardDisabled?:boolean;onDashboard?:()=>void}){
 const {enabled}=useMotionPreference(),systemReduced=useReducedMotion(),reduced=!enabled||!!systemReduced;const [filter,setFilter]=useState<Verdict|'all'>('all'),[tooltip,setTooltip]=useState<{item:Item;left:number;top:number;below:boolean}|null>(null);
 const items=run.items,counts=Object.fromEntries(verdicts.map(status=>[status,items.filter(item=>item.status===status).length])) as Record<Verdict,number>,completed=counts.pass+counts.fail+counts.review,attention=counts.fail+counts.review;
 const chartDocuments=run.documents.filter(document=>document.role==='target').map(document=>({id:document.id,name:document.name,...Object.fromEntries(verdicts.map(status=>[status,items.filter(item=>item.documentId===document.id&&item.status===status).length]))}));for(const documentId of new Set(items.map(item=>item.documentId)))if(!chartDocuments.some(document=>document.id===documentId))chartDocuments.push({id:documentId,name:'검토 문서',...Object.fromEntries(verdicts.map(status=>[status,items.filter(item=>item.documentId===documentId&&item.status===status).length]))});
 const slices=verdicts.filter(status=>counts[status]>0).map(status=>({status,name:statusLabels[status],value:counts[status],fill:colors[status]})),pieData=items.length?slices:[{status:'pending' as const,name:'판정 대기',value:1,fill:'#263943'}],visible=items.filter(item=>filter==='all'||item.status===filter);
 const enter=(delay=0)=>({initial:{opacity:0,y:reduced?0:10},animate:{opacity:1,y:0},transition:{duration:reduced?0:.5,ease,delay:reduced?0:delay}}),toggle=(status:Verdict)=>{setFilter(current=>current===status?'all':status);setTooltip(null);};
 const openTooltip=(item:Item,element:HTMLElement)=>{const rect=element.getBoundingClientRect(),below=rect.top<220;setTooltip({item,left:Math.max(12,Math.min(rect.left+rect.width/2-140,window.innerWidth-292)),top:below?rect.bottom+9:rect.top-9,below});};
 return <section className="results-visuals" aria-label="검토 결과 시각화"><motion.header className="rv-header" {...enter()}><div className="rv-heading"><span className="rv-heading-icon"><FileCheck2 size={19}/></span><h2>검토 결과</h2><span className="rv-heading-note">판정부터 근거까지, 한눈에.</span></div>{showDashboardButton&&<motion.button className="rv-dashboard" disabled={dashboardDisabled} onClick={onDashboard} whileHover={reduced?undefined:{y:-2}} whileTap={reduced?undefined:{scale:.98}}><Sparkles size={15}/><span>나만의 대시보드</span><ArrowUpRight size={15}/></motion.button>}</motion.header>
 <motion.div className="rv-kpis" {...enter(.04)}><div className="rv-kpi"><span className="rv-kpi-icon cyan"><FileText size={19}/></span><div><span className="rv-kpi-label">검토 문서</span><div className="rv-kpi-number"><Count value={chartDocuments.length} reduced={reduced}/><small>개</small></div></div><span className="rv-mini-sheets" aria-hidden="true"><i/><i/><i/></span></div><div className="rv-kpi"><span className="rv-kpi-icon lime"><Layers3 size={19}/></span><div><span className="rv-kpi-label">판정한 항목</span><div className="rv-kpi-number"><Count value={completed} reduced={reduced}/><small>/ {items.length}</small></div></div><span className="rv-mini-bars" aria-hidden="true">{verdicts.map(status=><i key={status} style={{background:colors[status],height:items.length?`${Math.max(3,counts[status]/items.length*30)}px`:'3px'}}/>)}</span></div><div className="rv-kpi" aria-label={`부적합 ${counts.fail}개와 확인 필요 ${counts.review}개를 합친 확인할 항목 ${attention}개`}><span className="rv-kpi-icon amber"><HelpCircle size={19}/></span><div><span className="rv-kpi-label">확인할 항목</span><div className="rv-kpi-number"><Count value={attention} reduced={reduced}/><small>개</small></div></div><span className="rv-attention-dots" aria-hidden="true">{Array.from({length:6},(_,index)=><i className={index<Math.min(6,attention)?'lit':''} key={index}/>)}</span></div></motion.div>
 <div className="rv-chart-grid"><motion.section className="rv-chart-panel rv-verdict-panel" aria-label={`판정 분포: 적합 ${counts.pass}, 부적합 ${counts.fail}, 확인 필요 ${counts.review}, 대조 중 ${counts.pending}`} {...enter(.08)}><div className="rv-panel-heading"><h3>판정 분포</h3><span>색상을 눌러 필터</span></div><div className="rv-donut-area"><ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={0}><PieChart accessibilityLayer><Pie data={pieData} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius="68%" outerRadius="90%" startAngle={90} endAngle={-270} paddingAngle={slices.length>1?4:0} stroke="none" cornerRadius={5} isAnimationActive={!reduced&&items.length>0} animationDuration={850} animationEasing="ease-out" onClick={slice=>{if(items.length)toggle((slice as unknown as {status:Verdict}).status);}}>{pieData.map(slice=><Cell key={slice.status} fill={slice.fill} opacity={filter==='all'||filter===slice.status?1:.26} cursor={items.length?'pointer':'default'}/>)}</Pie>{items.length>0&&<Tooltip content={({active,payload}:any)=>active&&payload?.[0]?<div className="rv-chart-tooltip"><i style={{background:String(payload[0].payload.fill)}}/><span>{payload[0].name}</span><b>{payload[0].value}</b></div>:null}/>}</PieChart></ResponsiveContainer><div className="rv-donut-center"><Count value={filter==='all'?items.length:counts[filter]} reduced={reduced}/><span>{filter==='all'?'전체 항목':statusLabels[filter]}</span></div></div></motion.section>
 <motion.section className="rv-chart-panel rv-documents-panel" aria-label="문서별 판정 항목 수" {...enter(.12)}><div className="rv-panel-heading"><h3>문서별 결과</h3><span>{chartDocuments.length}개 검토 문서</span></div><div className="rv-document-scroll">{chartDocuments.length?<div className="rv-document-chart" style={{height:Math.max(104,chartDocuments.length*37+22)}}><ResponsiveContainer width="100%" height="100%" minWidth={0}><BarChart data={chartDocuments} layout="vertical" margin={{top:4,right:12,bottom:0,left:0}} barSize={14}><XAxis type="number" allowDecimals={false} axisLine={false} tickLine={false} tick={{fill:'#859eaa',fontSize:10}} minTickGap={16}/><YAxis type="category" dataKey="name" width={105} axisLine={false} tickLine={false} tickFormatter={name=>shortName(String(name),13)} tick={{fill:'#c6d7de',fontSize:11}}/><Tooltip cursor={{fill:'#bfe6ed08'}} content={({active,payload,label}:any)=>active&&payload?.length?<div className="rv-chart-tooltip rv-doc-tooltip"><strong>{label}</strong>{payload.filter((entry:any)=>Number(entry.value)>0).map((entry:any)=><span key={String(entry.dataKey)}><i style={{background:entry.color}}/>{entry.name}<b>{entry.value}</b></span>)}</div>:null}/>{verdicts.map(status=><Bar key={status} name={statusLabels[status]} dataKey={status} stackId="verdicts" fill={colors[status]} opacity={filter==='all'||filter===status?1:.23} radius={[2,2,2,2]} isAnimationActive={!reduced} animationDuration={800} animationEasing="ease-out"/>)}</BarChart></ResponsiveContainer></div>:<div className="rv-small-empty"><FileText size={30} strokeWidth={1.2}/><span>검토 문서를 기다리고 있습니다.</span></div>}</div></motion.section></div>
 <motion.section className="rv-item-panel" aria-label="항목별 결과" {...enter(.16)}><div className="rv-item-heading"><div className="rv-panel-heading"><h3>항목별 결과</h3><span>항목을 눌러 원문과 근거 보기<ArrowUpRight size={11}/></span></div><div className="rv-legend" aria-label="판정별 항목 필터"><button className={filter==='all'?'active':''} aria-pressed={filter==='all'} onClick={()=>{setFilter('all');setTooltip(null);}}>전체<b>{items.length}</b></button>{verdicts.filter(status=>status!=='pending'||counts.pending>0).map(status=><button key={status} className={filter===status?'active':''} aria-pressed={filter===status} style={{'--rv-color':colors[status]} as CSSProperties} onClick={()=>toggle(status)}><i/>{statusLabels[status]}<b>{counts[status]}</b></button>)}</div></div><div className="rv-item-scroll" onScroll={()=>setTooltip(null)}><motion.div className="rv-item-grid" layout={!reduced}><AnimatePresence mode="popLayout" initial={false}>{visible.map((item,index)=><ResultTile key={item.id} item={item} index={index} reduced={reduced} described={tooltip?.item.id===item.id} onSelect={()=>onSelectItem(item.id)} onOpen={element=>openTooltip(item,element)} onClose={()=>setTooltip(null)}/>)}</AnimatePresence></motion.div>{!visible.length&&<div className="rv-map-empty"><span className="rv-empty-mosaic" aria-hidden="true">{Array.from({length:9},(_,index)=><i key={index}/>)}</span><span>{items.length?'이 판정에 해당하는 항목이 없습니다.':'검토 결과가 도착하면 여기에 표시됩니다.'}</span></div>}</div></motion.section>
 {typeof document!=='undefined'&&createPortal(<AnimatePresence>{tooltip&&<motion.div id="rv-item-tooltip" role="tooltip" className={`rv-item-tooltip ${tooltip.below?'below':'above'}`} style={{left:tooltip.left,top:tooltip.top,'--rv-color':colors[tooltip.item.status]} as CSSProperties} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:.12}}><span className="rv-tooltip-document">{run.documents.find(doc=>doc.id===tooltip.item.documentId)?.name||'검토 문서'}</span><div className="rv-tooltip-heading"><strong>{tooltip.item.label}</strong><span>{statusLabels[tooltip.item.status]}</span></div><p><b>원문 값</b> {formatValue(tooltip.item.value)} {tooltip.item.unit}</p>{tooltip.item.criterion&&<p><b>판정 기준</b> {tooltip.item.criterion}</p>}{tooltip.item.explanation&&<p>{tooltip.item.explanation}</p>}<small>클릭하여 원문과 근거 보기<ArrowUpRight size={11}/></small></motion.div>}</AnimatePresence>,document.body)}</section>;
}
