import {Fragment} from 'react';
import type {Evidence,Item} from '../types';
import {itemPriority,sourceEvidence,textMatches} from '../source-highlights';
export default function SourceText({text,items,documentId,evidence,selectedItemId,onSelectItem}:{text:string;items:Item[];documentId:string;evidence:Evidence[];selectedItemId?:string|null;onSelectItem?:(id:string)=>void}){
 const highlights=items.filter(item=>sourceEvidence(item,documentId).length);const ranges=highlights.flatMap(item=>sourceEvidence(item,documentId).filter(e=>e.quote).flatMap(e=>textMatches(text,e.quote!).map(range=>({...range,item}))));
 if(highlights.length){const points=[...new Set([0,text.length,...ranges.flatMap(r=>[r.start,r.end])])].sort((a,b)=>a-b);return <>{points.slice(0,-1).map((start,index)=>{const end=points[index+1],item=ranges.filter(r=>r.start<=start&&r.end>=end).sort((a,b)=>itemPriority(a.item,selectedItemId)-itemPriority(b.item,selectedItemId))[0]?.item;return item?<button key={start} className={`doc-preview__text-highlight source-mark--${item.status} ${item.id===selectedItemId?'is-selected':''}`} onClick={()=>onSelectItem?.(item.id)}>{text.slice(start,end)}</button>:<Fragment key={start}>{text.slice(start,end)}</Fragment>;})}</>;}
 const rawRanges:{start:number;end:number}[]=[];for(const e of evidence){if(!e.quote?.trim())continue;let offset=0;for(let i=0;i<30;i++){const start=text.indexOf(e.quote,offset);if(start<0)break;const end=start+e.quote.length;rawRanges.push({start,end});offset=end;}}
 const merged:{start:number;end:number}[]=[];for(const range of rawRanges.sort((a,b)=>a.start-b.start)){const previous=merged.at(-1);if(previous&&range.start<=previous.end)previous.end=Math.max(previous.end,range.end);else merged.push({...range});}let cursor=0;const parts=merged.map(range=>{const start=cursor;cursor=range.end;return <Fragment key={range.start}>{text.slice(start,range.start)}<mark>{text.slice(range.start,range.end)}</mark></Fragment>;});return <>{parts}{text.slice(cursor)}</>;
}
