import React from 'react';
import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';
import { Doughnut, Pie, PolarArea, Bar } from 'react-chartjs-2';
import { Chart, ArcElement, BarElement, CategoryScale, LinearScale, RadialLinearScale, Tooltip, Legend } from 'chart.js';

Chart.register(ArcElement, BarElement, CategoryScale, LinearScale, RadialLinearScale, Tooltip, Legend);
const instances = new WeakMap();

// Trusted React chart components are bundled once, not generated by the model.
// The complete bundle is embedded in exports so they also work offline.
function mount(element, config, reduced = false) {
  const existing = instances.get(element);
  if (existing) { existing.update(config, reduced); return existing; }
  const root = createRoot(element);
  let chart = null;
  let frame = null;
  const render = (next, reduceMotion) => {
    const Component = { bar: Bar, pie: Pie, polarArea: PolarArea, doughnut: Doughnut }[next.type] || Doughnut;
    const options = {
      ...next.options,
      responsive: true,
      maintainAspectRatio: false,
      animation: reduceMotion ? false : (next.options?.animation ?? { duration: 900, easing: 'easeOutQuart' }),
    };
    flushSync(() => root.render(<Component
      ref={instance => { chart = instance; }}
      data={next.data}
      options={options}
      role="img"
      aria-label={element.getAttribute('aria-label') || '검토 결과 차트'}
    />));
  };
  const controller = {
    update(next, reduceMotion = reduced) { render(next, reduceMotion); },
    destroy() { if (frame !== null) cancelAnimationFrame(frame); flushSync(() => root.unmount()); instances.delete(element); },
    inspect() {
      if (!chart) return null;
      return {
        type: chart.config.type,
        labels: [...chart.data.labels],
        datasets: chart.data.datasets.map(dataset => ({ label: dataset.label || '', data: [...dataset.data] })),
        animated: chart.options.animation !== false,
        cutout: chart.options.cutout ?? null,
        colors: [...(chart.data.datasets[0]?.backgroundColor || [])],
      };
    },
  };
  instances.set(element, controller);
  render(config, reduced);
  // Let the responsive canvas receive its first measured size before the reveal.
  // The initial ResizeObserver notification otherwise cancels Chart.js's entrance.
  if (!reduced && config.options?.animation !== false && typeof requestAnimationFrame === 'function') {
    frame = requestAnimationFrame(() => {
      frame = requestAnimationFrame(() => {
        frame = null;
        if (chart && instances.has(element)) { chart.reset(); chart.update(); }
      });
    });
  }
  return controller;
}

window.TraceCharts = Object.freeze({
  version: 'react-chartjs-2@5.3.1',
  mount,
  inspect(element) { return instances.get(element)?.inspect() ?? null; },
});
