import type {ActivityEvent,ActivityTask} from './types';

export const isActiveTask=(task:ActivityTask)=>task.status==='running'||task.status==='queued';
export const isExecutingTask=(task:ActivityTask)=>task.status==='running'&&!task.waitingForTaskId;
export const groupKey=(task:ActivityTask)=>task.documentId||task.contextId||task.id;
export function normalizeActivity(value:unknown):ActivityTask[]{if(!Array.isArray(value))return [];return value.filter(task=>task&&typeof task.id==='string'&&task.id&&['queued','running','completed','failed','cancelled'].includes(task.status)).slice(-100).map(task=>({...task,events:(Array.isArray(task.events)?task.events:[]).slice(-200).filter((event:any)=>event&&typeof event.title==='string'&&event.title.trim()),history:task.history||{eventLimit:200,logLimit:200,omittedEvents:0,omittedLogs:0}}));}
export type ActivityScope={runId?:string|null;contextId?:string|null;startedAfter?:number|string;taskKinds?:string[];documentNames?:string[]};
export function scopeActivity(tasks:ActivityTask[],scope:ActivityScope){const cutoff=typeof scope.startedAfter==='number'?scope.startedAfter:scope.startedAfter?Date.parse(scope.startedAfter):NaN;return tasks.filter(task=>{if(scope.runId!==undefined&&(scope.runId===null||task.runId!==scope.runId))return false;if(scope.contextId!==undefined&&(!scope.contextId||(task.contextId||(task as any).dashboardId)!==scope.contextId))return false;if(Number.isFinite(cutoff)&&!(Date.parse(task.startedAt)>=cutoff))return false;if(scope.taskKinds?.length&&!scope.taskKinds.includes(task.kind))return false;if(scope.documentNames?.length){const title=String(task.title||'').toLowerCase().replace(/\s/g,'');if(!scope.documentNames.some(name=>{const normalized=name.toLowerCase().replace(/\s/g,'');return title.includes(normalized)||(normalized.length>48&&title.includes(normalized.slice(0,48)));}))return false;}return true;});}
export function activityGroups(tasks:ActivityTask[]){const byId=new Map(tasks.map(task=>[task.id,task]));const identity=(task:ActivityTask,visited=new Set<string>()):string=>{if(visited.has(task.id))return `task:${task.id}`;visited.add(task.id);if(task.documentId)return `document:${task.contextId||task.runId||''}:${task.documentId}`;if(task.kind==='dashboard'&&(task.contextId||(task as any).dashboardId))return `dashboard:${task.contextId||(task as any).dashboardId||task.runId||'current'}`;const parent=task.parentTaskId?byId.get(task.parentTaskId):undefined;return parent?identity(parent,visited):`task:${task.id}`;};const groups=new Map<string,ActivityTask[]>();for(const task of tasks){const id=identity(task);groups.set(id,[...(groups.get(id)||[]),task]);}return [...groups].map(([id,tasks])=>({id,tasks:orderedTasks(tasks)}));}
export function orderedTasks(tasks:ActivityTask[]){return [...tasks].sort((a,b)=>Date.parse(a.startedAt)-Date.parse(b.startedAt));}
export function preferredTask(tasks:ActivityTask[]){const sorted=orderedTasks(tasks);return sorted.filter(isExecutingTask).at(-1)||sorted.find(isActiveTask)||sorted.at(-1);}
export function phaseLabel(task:ActivityTask){if(task.status==='queued')return '대기';if(task.status==='completed')return '완료';if(task.status==='failed')return '확인 필요';if(task.status==='cancelled')return '중단';const labels:Record<string,string>={ready:'준비',prepare:'준비',create:'준비',upload:'원본 전달',read:'문서 읽기',reread:'원본 재조회',transcribe:'시각 읽기',structure:'구조 파악',profile:'전체 구조',explore:'구조 탐색',context:'맥락 이해',model:task.kind==='dashboard'?'화면 설계':'내용 이해',extract:task.kind==='criteria'?'기준 추출':'항목 추출',install:'도구 설치',build:'화면 제작',repair:'보완',quality:'검증',verify:'검증',validate:'검증',retry:'재검토',cleanup:'마무리',complete:'완료',work:'작업'};return labels[task.phase]||'작업 중';}
export function workStage(task?:ActivityTask){if(!task)return 0;const phase=task.phase;if(task.status==='completed'||phase==='complete'||phase==='cleanup')return 4;if(task.status==='queued')return 0;if(task.kind==='dashboard')return phase==='install'?1:['model','build','repair','work'].includes(phase)?2:['validate','verify'].includes(phase)?3:0;return ['read','reread','transcribe'].includes(phase)?1:['structure','profile','explore'].includes(phase)?2:['context','model','extract','quality','verify','validate','repair','retry','work'].includes(phase)?3:0;}
export function workSteps(task?:ActivityTask){if(task?.kind==='dashboard')return ['준비','설치','제작','검증','정리'];const labels=['준비','읽기','구조','맥락','정리'],phase=task?.phase; if(phase==='install')labels[0]='도구 설치';if(phase==='reread')labels[1]='재조회';if(phase==='transcribe')labels[1]='시각 읽기';if(phase==='profile')labels[2]='전체 구조';if(phase==='extract')labels[3]=task?.kind==='criteria'?'기준 추출':'항목 추출';if(['quality','validate','verify'].includes(phase||''))labels[3]='검증';if(phase==='retry')labels[3]='재검토';if(phase==='repair')labels[3]='보완';return labels;}

export type Handoff={key:string;from:ActivityTask;to:ActivityTask;event:ActivityEvent;time:number;direction:'forward'|'backward';sequence:number};
function agree(a:ActivityTask,b:ActivityTask){return (['documentId','runId','contextId'] as const).every(key=>!a[key]||!b[key]||a[key]===b[key]);}
/** A transfer has a causal witness; neighboring runtimes alone cannot create one. */
export function handoffCandidates(tasks:ActivityTask[]){const byId=new Map(tasks.map(task=>[task.id,task])),found=new Map<string,Handoff>();let sequence=0;const add=(fromId:string,toId:string,event:ActivityEvent,rawKey:string)=>{const from=byId.get(fromId),to=byId.get(toId);if(!from||!to||from.runtime===to.runtime||!agree(from,to))return;const key=to.parentTaskId===from.id?`parent:${from.id}:${to.id}`:rawKey;if(!found.has(key))found.set(key,{key,from,to,event,time:Date.parse(event.time),direction:from.runtime==='e2b'?'forward':'backward',sequence:sequence++});};for(const task of tasks){if(task.parentTaskId){const first=task.events.find(event=>!event.log&&event.status==='running');if(first)add(task.parentTaskId,task.id,first,`start:${task.id}:${first.id}`);}for(const event of task.events)if(!event.log&&event.handoff)add(event.handoff.fromTaskId,event.handoff.toTaskId,event,`handoff:${event.id}`);}return [...found.values()].sort((a,b)=>a.time-b.time||a.sequence-b.sequence);}
const boundedRemember=(set:Set<string>,key:string,max:number,touch=false)=>{if(touch)set.delete(key);set.add(key);while(set.size>max)set.delete(set.values().next().value!);};
export class HandoffQueue {
 pending:Handoff[]=[];seen=new Set<string>();omitted=0;
 enqueue(values:Handoff[]){for(const value of values){if(this.seen.has(value.key)){boundedRemember(this.seen,value.key,256,true);continue;}boundedRemember(this.seen,value.key,256,true);this.pending.push(value);}this.pending.sort((a,b)=>a.time-b.time||a.sequence-b.sequence);while(this.pending.length>8){this.pending.shift();this.omitted++;}}
 take(){const next=this.pending.shift();if(next)boundedRemember(this.seen,next.key,256,true);return next;}
 clearPending(){for(const value of this.pending)boundedRemember(this.seen,value.key,256,true);this.pending=[];}
 reset(){this.pending=[];this.seen.clear();this.omitted=0;}
}
type ActivitySession={seen:Set<string>;visited:Set<string>;liveSince:number};
const sessions=new Map<string,ActivitySession>();
export function activitySession(key:string,cutoff?:number){let session=sessions.get(key);if(!session){session={seen:new Set(),visited:new Set(),liveSince:cutoff!==undefined&&Number.isFinite(cutoff)?cutoff:Date.now()};sessions.set(key,session);while(sessions.size>30)sessions.delete(sessions.keys().next().value!);}return session;}
export function rememberTransfer(session:ActivitySession,key:string){boundedRemember(session.seen,key,512);}
export function visitGroup(session:ActivitySession,key:string){boundedRemember(session.visited,key,100);}
export function recentTrail(tasks:ActivityTask[]){const entries=new Map<string,{task:ActivityTask;event:ActivityEvent}>();for(const task of tasks)for(const event of task.events){if(event.log||!event.title||!(['upload','files','read','reread','transcribe','structure','profile','explore','context','model','extract','quality','verify','validate','build','repair'].includes(event.step||'')||/수신|전달|읽기|추출|검증/.test(event.title)))continue;const key=`${task.id}:${event.title}`;entries.delete(key);entries.set(key,{task,event});}return [...entries.values()].sort((a,b)=>Date.parse(a.event.time)-Date.parse(b.event.time)).slice(-3);}
