import type {Criterion,Doc,Evidence,SubmittedCriterion} from './types';

export const signs={lt:'<',lte:'≤',gt:'>',gte:'≥',eq:'=',range:'~'};
export type CriteriaDraft=SubmittedCriterion&{included:boolean;expanded:boolean;editorMode:'numeric'|'qualitative'|'choose';rawValue:string;rawUpper:string;rawUnit:string;rawOperator:keyof typeof signs;rawPath:string;rawConditions:string;issues:string[]};
export const criteriaRefs=(criterion:Criterion):Evidence[]=>Array.isArray(criterion.sourceEvidence)?criterion.sourceEvidence:criterion.sourceEvidence?[criterion.sourceEvidence]:[];
const nonempty=(value:unknown):value is string=>typeof value==='string'&&value.trim().length>0;
export const cleanLines=(value:string)=>[...new Set(value.split('\n').map(line=>line.trim()).filter(Boolean))];
export const pathLines=(value:string)=>value.split('\n').map(line=>line.trim()).filter(Boolean);
export const createCriteriaDraft=(criterion:Criterion):CriteriaDraft=>({...criterion,included:true,expanded:false,editorMode:criterion.comparison?'numeric':'qualitative',rawValue:criterion.comparison?String(criterion.comparison.value):'',rawUpper:criterion.comparison?.upper===undefined?'':String(criterion.comparison.upper),rawUnit:criterion.comparison?.unit||'',rawOperator:criterion.comparison?.operator||'lte',rawPath:criterion.categoryPath?.join('\n')||'',rawConditions:criterion.conditions?.join('\n')||'',issues:[]});
export function mentionsSource(description:string,token:string){if(!nonempty(description)||!nonempty(token))return false;if(description.trim()===token)return true;const escaped=token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp('(?:^|[\\s\\[({<"\':;,/\\\\])'+escaped+'(?=$|[\\s\\])}>"\':;,!])','u').test(description);}
export function criterionSources(criterion:Criterion,documents:Doc[],inputMode='file'):string[]{
 const source=criterion.source&&typeof criterion.source==='object'?criterion.source as Record<string,unknown>:undefined;
 const description=typeof criterion.source==='string'?criterion.source:'';
 const ids=[criterion.sourceDocumentId,source?.documentId,...criteriaRefs(criterion).map(e=>e.documentId)].filter(nonempty);
 const inventory=new Map(documents.filter(d=>d.role==='criteria').map(d=>[d.id,d]));const destinations=new Set<string>();
 for(const id of ids){if(inventory.has(id))destinations.add(`file:${id}`);else if(id==='natural-language')destinations.add('text');}
 if(!destinations.size){for(const doc of inventory.values())if(mentionsSource(description,doc.id))destinations.add(`file:${doc.id}`);}
 if(!destinations.size){const counts=new Map<string,number>();for(const doc of inventory.values())counts.set(doc.name,(counts.get(doc.name)||0)+1);for(const doc of inventory.values())if(counts.get(doc.name)===1&&(criterion.sourceName===doc.name||mentionsSource(description,doc.name)))destinations.add(`file:${doc.id}`);}
 if(destinations.size)return [...destinations];
 const marker=[description,criterion.sourceName,source?.type,source?.kind,source?.origin].filter(nonempty).join(' ');
 const hasMetadata=ids.length>0||!!marker||!!source&&Object.keys(source).length>0;
 if(/사용자\s*(?:입력|요청|지시)|직접\s*입력|자연어|\b(?:natural(?:[_ -]language)?|user(?:[_ -]?(?:text|input|request))?|manual)\b/i.test(marker)||!hasMetadata&&(['text','natural','natural-language','natural_language','usertext','manual'].includes(inputMode)||/^(human-|revision-)/.test(criterion.id)))return ['text'];
 return ['unlocated'];
}
export function numericRule(draft:CriteriaDraft){const label=draft.label.trim(),unit=draft.rawUnit.trim(),scope=draft.scope?.trim(),conditions=cleanLines(draft.rawConditions);const value=draft.rawOperator==='range'?`${draft.rawValue} ~ ${draft.rawUpper}${unit?' '+unit:''} (양 끝 포함)`:`${signs[draft.rawOperator]} ${draft.rawValue}${unit?' '+unit:''}`;return `${label}: ${value}${scope?' · 적용 대상: '+scope:''}${conditions.length?' · 조건: '+conditions.join(', '):''}`;}
export function updateCriteriaDraft(draft:CriteriaDraft,patch:Partial<CriteriaDraft>):CriteriaDraft{const next={...draft,...patch,issues:[]};if(next.editorMode==='numeric'&&['label','scope','rawConditions','rawValue','rawUpper','rawOperator','rawUnit','editorMode'].some(key=>key in patch))next.rule=numericRule(next);return next;}
export function draftIssues(draft:CriteriaDraft){const issues:string[]=[];const path=pathLines(draft.rawPath),conditions=cleanLines(draft.rawConditions);if(!draft.label.trim())issues.push('항목명을 입력해 주세요.');else if(draft.label.length>500)issues.push('항목명은 500자 이내로 입력해 주세요.');if(!draft.rule.trim())issues.push('판정 기준을 입력해 주세요.');else if(draft.rule.length>4000)issues.push('판정 기준은 4000자 이내로 입력해 주세요.');if((draft.scope?.length||0)>500)issues.push('적용 대상은 500자 이내로 입력해 주세요.');if((draft.sampleName?.length||0)>300)issues.push('시료·제품명은 300자 이내로 입력해 주세요.');if(path.length>8||path.some(line=>line.length>200))issues.push('유형 경로는 최대 8단계, 단계당 200자까지 입력할 수 있습니다.');if(conditions.length>12||conditions.some(line=>line.length>500))issues.push('적용 조건은 최대 12개, 조건당 500자까지 입력할 수 있습니다.');if(draft.rawUnit.length>80)issues.push('단위는 80자 이내로 입력해 주세요.');if(draft.editorMode==='choose')issues.push('수정한 기준이 수치 기준인지 정성 기준인지 선택해 주세요.');if(draft.editorMode==='numeric'){if(!draft.rawValue.trim()||draft.rawValue.length>100||!Number.isFinite(Number(draft.rawValue)))issues.push('유효한 기준값을 입력해 주세요.');if(draft.rawOperator==='range'&&(!draft.rawUpper.trim()||draft.rawUpper.length>100||!Number.isFinite(Number(draft.rawUpper))||Number(draft.rawUpper)<Number(draft.rawValue)))issues.push('상한은 하한 이상의 숫자여야 합니다.');}return issues;}
export function serializeCriteriaDraft(draft:CriteriaDraft,revision=false):SubmittedCriterion{
 const {included,expanded,editorMode,rawValue,rawUpper,rawUnit,rawOperator,rawPath,rawConditions,issues:oldIssues,comparison,comparatorConfirmed,draftState,...criterion}=draft;
 const issues=draftIssues(draft),numberValid=rawValue.trim()!==''&&rawValue.length<=100&&Number.isFinite(Number(rawValue))&&(rawOperator!=='range'||rawUpper.trim()!==''&&rawUpper.length<=100&&Number.isFinite(Number(rawUpper))&&Number(rawUpper)>=Number(rawValue));
 return {...criterion,label:criterion.label.trim(),rule:criterion.rule.trim(),scope:criterion.scope?.trim(),sampleName:criterion.sampleName?.trim(),categoryPath:pathLines(rawPath),conditions:cleanLines(rawConditions),needsConfirmation:revision?(issues.length>0||!!criterion.needsConfirmation):false,...(editorMode==='numeric'&&numberValid?{comparison:{operator:rawOperator,value:Number(rawValue),...(rawOperator==='range'?{upper:Number(rawUpper)}:{}),unit:rawUnit.trim()},comparatorConfirmed:true}:{}),...(revision?{draftState:{mode:editorMode,operator:rawOperator,value:rawValue,upper:rawUpper,unit:rawUnit,issues}}:{})};
}
