import type {Evidence,Item} from './types';
export type NormalizedPreview={type?:string;text?:string;sheets:{name:string;rows:string[][];state?:string}[];warnings:string[];truncated:boolean};
export function normalizePreview(value:unknown):NormalizedPreview{
 const preview=value&&typeof value==='object'?value as Record<string,unknown>:{};
 const sheets=Array.isArray(preview.sheets)?preview.sheets.flatMap(value=>{if(!value||typeof value!=='object')return [];const sheet=value as Record<string,unknown>;if(typeof sheet.name!=='string'||!Array.isArray(sheet.rows))return [];return [{name:sheet.name,rows:sheet.rows.filter(Array.isArray).map(row=>row.map(cell=>cell==null?'':String(cell))),state:typeof sheet.state==='string'?sheet.state:undefined}];}):[];
 return {type:typeof preview.type==='string'?preview.type:undefined,text:typeof preview.text==='string'?preview.text:undefined,sheets,warnings:Array.isArray(preview.warnings)?preview.warnings.filter((warning):warning is string=>typeof warning==='string'):[],truncated:preview.truncated===true};
}
export function previewRenderer(document:{name:string;mime:string},preview:NormalizedPreview){
 if(document.mime==='application/pdf'||preview.type==='pdf'||/\.pdf$/i.test(document.name))return 'pdf';
 if(document.mime.startsWith('image/')||preview.type==='image')return 'image';
 if(preview.sheets.length)return 'table';
 return preview.text!==undefined?'text':'unsupported';
}
export function requestedPdfPage(page:unknown,pageCount:number){return typeof page==='number'&&Number.isInteger(page)&&page>0&&page<=pageCount?page:null;}
// The baseline chip path intentionally accepts in-range fractional pages.
export function sourceChipPdfPage(sources:Evidence[],pageCount:number){const page=sources.find(source=>source.page)?.page;return page&&page>=1&&page<=pageCount?page:null;}
export function isMissingItem(item:Item){if(item.presence==='present'||item.presence==='unreadable')return false;if(item.presence==='missing'||item.missingVerified===true)return true;return typeof item.value==='string'&&/^\s*(?:누락|미기재|미제출|해당 항목 없음|missing|not provided|not reported|not present)\s*$/i.test(item.value);}
export function sourceEvidence(item:Item,documentId:string){return (item.evidence||[]).filter(e=>e.documentId===documentId&&!(isMissingItem(item)&&item.documentId===documentId));}
export function sourceChip(item:Item,documentId:string,location:{page?:number;sheet?:string},placed:boolean,compact:boolean){
 const sources=sourceEvidence(item,documentId),missing=isMissingItem(item)&&item.documentId===documentId;
 const elsewhere=(source:Evidence)=>!!(location.page&&source.page&&source.page!==location.page||location.sheet&&source.sheet&&source.sheet.toLowerCase()!==location.sheet.toLowerCase()&&source.sheet.toLowerCase()!=='csv');
 const allElsewhere=!!sources.length&&sources.every(elsewhere),other=sources.find(elsewhere);
 const hint=allElsewhere&&other?(other.page?`${other.page}p`:other.sheet||'위치 확인'):missing?'항목 누락':!sources.length?'근거 없음':placed?'':'위치 확인';
 return {visible:!compact||!placed&&!allElsewhere,hint,description:missing?'원문에서 해당 항목을 찾지 못했습니다':!sources.length?'연결된 원문 근거가 없습니다':!placed&&!allElsewhere?'현재 원문에서 근거 위치를 확인해 주세요':''};
}
export function itemPriority(item:Item,selectedId?:string|null){return item.id===selectedId?-1:({fail:0,review:1,pending:2,pass:3}[item.status]);}
function normalize(text:string){let value='',offsets:number[]=[];for(let i=0;i<text.length;i++){if(/\s/u.test(text[i])){if(value.endsWith(' '))continue;value+=' ';offsets.push(i);}else{value+=text[i];offsets.push(i);}}return {value,offsets};}
export function textMatches(text:string,quote:string):{start:number;end:number}[]{
 const source=normalize(text),needle=normalize(quote.trim()).value;if(!needle)return [];const out:{start:number;end:number}[]=[];const numbers=[...source.value.matchAll(/[+\-−±]?(?:(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?|\.\d+)(?:[eE][+\-]?\d+)?/g)].map(m=>({start:m.index!,end:m.index!+m[0].length}));
 for(let offset=0;offset<=source.value.length-needle.length;){const start=source.value.indexOf(needle,offset);if(start<0)break;const end=start+needle.length;offset=start+1;const cutsNumber=numbers.some(n=>start<n.end&&end>n.start&&(start>n.start||end<n.end));if(!cutsNumber)out.push({start:source.offsets[start],end:(source.offsets[end-1]??text.length-1)+1});}return out;
}
function splitAddress(text:string){const entries:string[]=[];let current='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==="'"){if(quoted&&text[i+1]==="'"){current+="''";i++;continue;}quoted=!quoted;}if((c===','||c===';')&&!quoted){entries.push(current.trim());current='';}else current+=c;}if(quoted)return null;entries.push(current.trim());return entries.filter(Boolean);}
export function evidenceSheet(evidence:Evidence,sheetNames:string[]){
 const qualifiers=[evidence.sheet].filter((name):name is string=>typeof name==='string'&&!!name);
 if(evidence.cell){if(typeof evidence.cell!=='string')return null;const entries=splitAddress(evidence.cell);if(!entries?.length)return null;for(const entry of entries){const match=/^(?:'((?:[^']|'')+)'|([^!]+))!(.+)$/.exec(entry);if(match)qualifiers.push((match[1]||match[2]).replace(/''/g,"'").trim());else if(entry.includes('!'))return null;}}
 const names=[...new Set(qualifiers.map(name=>name.toLowerCase()))];if(names.length>1||!names.length&&sheetNames.length!==1)return null;const requested=names[0]||sheetNames[0]?.toLowerCase();return sheetNames.find(name=>name.toLowerCase()===requested)||(sheetNames.length===1&&requested==='csv'?sheetNames[0]:null);
}
function cell(text:string){const m=/^\$?([a-z]+)\$?(\d+)$/i.exec(text);if(!m)return null;const column=[...m[1].toUpperCase()].reduce((a,c)=>a*26+c.charCodeAt(0)-64,0),row=Number(m[2]);return Number.isSafeInteger(column)&&Number.isSafeInteger(row)&&column>0&&row>0?{row,column}:null;}
export function tableEvidenceCells(evidence:Evidence,activeSheet:string,sheetNames:string[],rowCount:number,columnCount:number){
 const cells=new Set<string>();if(!evidence.cell)return {cells,ambiguous:false,hasAddress:false};if(typeof evidence.cell!=='string')return {cells,ambiguous:true,hasAddress:true};const entries=splitAddress(evidence.cell);if(!entries?.length)return {cells,ambiguous:true,hasAddress:true};const qualifiers=[evidence.sheet].filter(Boolean) as string[];const ranges:string[]=[];
 for(const entry of entries){const m=/^(?:'((?:[^']|'')+)'|([^!]+))!(.+)$/.exec(entry);if(m){qualifiers.push((m[1]||m[2]).replace(/''/g,"'").trim());ranges.push(m[3].trim());}else if(entry.includes('!'))return {cells,ambiguous:true,hasAddress:true};else ranges.push(entry);}
 const key=(value:string)=>value.toLocaleLowerCase();const unique=[...new Set(qualifiers.map(key))];if(unique.length>1||!unique.length&&sheetNames.length!==1)return {cells,ambiguous:true,hasAddress:true};const requested=unique[0]||key(sheetNames[0]);if(requested!==key(activeSheet)&&!(sheetNames.length===1&&requested==='csv'))return {cells,ambiguous:false,hasAddress:true};
 for(const range of ranges){let start:{row:number;column:number}|null=null,end:{row:number;column:number}|null=null;const rowOnly=/^(?:row\s*(\d+)|(\d+)\s*행|(\d+)\s*:\s*(\d+))$/i.exec(range);if(rowOnly){const a=Number(rowOnly[1]||rowOnly[2]||rowOnly[3]),b=Number(rowOnly[4]||a);if(!Number.isSafeInteger(a)||!Number.isSafeInteger(b)||a<1||b<1)return {cells:new Set<string>(),ambiguous:true,hasAddress:true};start={row:a,column:1};end={row:b,column:columnCount};}else{const parts=range.split(':');if(parts.length>2)return {cells:new Set<string>(),ambiguous:true,hasAddress:true};start=cell(parts[0].trim());end=cell((parts[1]||parts[0]).trim());}if(!start||!end)return {cells:new Set<string>(),ambiguous:true,hasAddress:true};for(let row=Math.max(1,Math.min(start.row,end.row));row<=Math.min(100,rowCount,Math.max(start.row,end.row));row++)for(let col=Math.max(1,Math.min(start.column,end.column));col<=Math.min(100,columnCount,Math.max(start.column,end.column));col++)cells.add(`${row-1}:${col-1}`);}
 return {cells:new Set([...cells].sort((a,b)=>{const [ar,ac]=a.split(':').map(Number),[br,bc]=b.split(':').map(Number);return ar-br||ac-bc;})),ambiguous:false,hasAddress:true};
}
export type PdfTextRun={text:string;x:number;y:number;width:number;height:number;dx:number;dy:number;hasEOL?:boolean;start?:number;end?:number};
export function pdfRunBox(item:any,viewportTransform:number[],styles:Record<string,any>):PdfTextRun|null{
 const m=item.transform,v=viewportTransform;if(!Array.isArray(m)||m.length!==6||!Array.isArray(v)||v.length!==6||![...m,...v,item.width,item.height].every(Number.isFinite)||item.width<=0||item.height<=0)return null;const [a,b,c,d,e,f]=[v[0]*m[0]+v[2]*m[1],v[1]*m[0]+v[3]*m[1],v[0]*m[2]+v[2]*m[3],v[1]*m[2]+v[3]*m[3],v[0]*m[4]+v[2]*m[5]+v[4],v[1]*m[4]+v[3]*m[5]+v[5]];const mx=Math.hypot(m[0],m[1]),my=Math.hypot(m[2],m[3]);if(!mx||!my)return null;const advance=[a*item.width/mx,b*item.width/mx],height=[c*item.height/my,d*item.height/my];const font=styles[item.fontName]||{};let ascent=Number.isFinite(font.ascent)?font.ascent:Number.isFinite(font.descent)?1+font.descent:1;if(ascent<=0||ascent>2)ascent=1;const origin=[e+(ascent-1)*height[0],f+(ascent-1)*height[1]];const xs=[origin[0],origin[0]+advance[0],origin[0]-height[0],origin[0]+advance[0]-height[0]],ys=[origin[1],origin[1]+advance[1],origin[1]-height[1],origin[1]+advance[1]-height[1]];const x=Math.min(...xs),y=Math.min(...ys),width=Math.max(...xs)-x,h=Math.max(...ys)-y;if(![x,y,width,h].every(Number.isFinite)||Math.abs(x)>1e8||Math.abs(y)>1e8||width>1e7||h>1e7)return null;const length=Math.hypot(a,b);if(!length)return null;return {text:item.str,x,y,width,height:h,dx:a/length,dy:b/length,hasEOL:item.hasEOL===true};
}
const sameRow=(a:PdfTextRun,b:PdfTextRun)=>a.dx*b.dx+a.dy*b.dy>=.98&&Math.abs((b.x-a.x)*-a.dy+(b.y-a.y)*a.dx)<=.4*Math.max(a.height,b.height);
export function pdfHighlightRuns(runs:PdfTextRun[],item:Item,documentId:string,page:number){
 const evidence=sourceEvidence(item,documentId).filter(e=>(!e.page||e.page===page)&&e.quote);if(!evidence.length)return [];
 let text='';const ranges=runs.map((run,index)=>{const previous=runs[index-1];let separator='';if(previous){const height=Math.max(run.height,previous.height),dot=run.dx*previous.dx+run.dy*previous.dy;const vertical=Math.abs((run.x-previous.x)*-previous.dy+(run.y-previous.y)*previous.dx),gap=run.x-(previous.x+previous.width);separator=dot<.98||vertical>3*height||vertical<=.35*height&&gap>3*height?'\0':previous.hasEOL||vertical>.35*height?'\n':Math.abs(gap)<=.12*height?'':' ';}text+=separator;const start=text.length;text+=run.text;return {...run,start,end:text.length,index};});
 const anchors=[...new Set([item.label,item.label.split(/[·›>]/).at(-1)||''].map(s=>s.trim()).filter(s=>s&&/\p{L}/u.test(s)))];const witnessRuns:typeof ranges=[];const quoted:{run:typeof ranges[number];named:boolean}[]=[];
 for(const e of evidence){for(const match of textMatches(text,e.quote!)){const matched=ranges.filter(r=>r.start<match.end&&r.end>match.start);if(text.slice(match.start,match.end).includes('\0'))continue;const witness=anchors.filter(label=>normalize(e.quote!).value.includes(normalize(label).value)).flatMap(label=>textMatches(text.slice(match.start,match.end),label).flatMap(m=>ranges.filter(r=>r.start<match.start+m.end&&r.end>match.start+m.start)));witnessRuns.push(...witness);quoted.push(...matched.map(run=>({run,named:witness.length>0})));}}
 if(!witnessRuns.length||witnessRuns.some(a=>!sameRow(a,witnessRuns[0])))return [];const anchor=witnessRuns[0];const result=new Map<number,PdfTextRun>();for(const {run:r,named} of quoted){if(!sameRow(anchor,r))continue;const duplicate=ranges.filter(x=>sameRow(anchor,x)&&x.text.trim()===r.text.trim()).length;if(named||duplicate===1)result.set(r.index,r);}return [...result.values()];
}
