import {useCallback,useEffect,useRef,useState} from 'react';
import {get,post} from './api';
import {ReviewRequestGate,reduceReview,terminal} from './review-state';
import type {ConfirmCriteriaRequest,Item,ReviewEvent,ReviewRun,StartRunRequest,ResolveItemResponse} from './types';

export function useReview(){
 const [run,setRun]=useState<ReviewRun|null>(null),[error,setError]=useState(''),[connecting,setConnecting]=useState(false),[pendingAction,setAction]=useState<string|null>(null),[connected,setConnected]=useState(false),[resolving,setResolving]=useState<string[]>([]);
 const gate=useRef(new ReviewRequestGate()),source=useRef<EventSource|null>(null),action=useRef<symbol|null>(null),resolveTokens=useRef(new Map<string,symbol>()),runRef=useRef(run);
 useEffect(()=>{runRef.current=run;},[run]);
 const close=useCallback(()=>{source.current?.close();source.current=null;setConnected(false);},[]);
 const remoteCancel=useCallback((id?:string)=>{if(id)void post(`/api/runs/${id}/cancel`).catch(()=>{});},[]);
 const snapshot=useCallback(async(command=false,t=gate.current.ticket())=>{const r=await get<ReviewRun>(`/api/runs/${t.runId}`);if(gate.current.snapshot(t,r,command)){setRun(r);return r;}return null;},[]);
 const connect=useCallback((id:string)=>{
  close();const ticket=gate.current.ticket();const es=new EventSource(`/api/runs/${id}/events?after=${ticket.sequence}`);source.current=es;let recovering=false;
  es.onopen=()=>{if(source.current===es&&gate.current.current(ticket)){setConnected(true);setConnecting(false);}};
  es.onmessage=(message)=>{if(source.current!==es)return;let event:ReviewEvent;try{event=JSON.parse(message.data);}catch{return;}if(!gate.current.event(ticket,event))return;setConnected(true);setRun(r=>reduceReview(r,event));
   if(terminal(String(event.runStatus||''))||['criteria.confirmation_required','criteria.revision.completed','criteria.revision.failed','criteria.confirmed','run.awaiting_documents'].includes(event.type))void snapshot().then(r=>{if(r&&terminal(r.status))close();}).catch(()=>{});
  };
  es.onerror=async()=>{if(source.current!==es||recovering||!gate.current.current(ticket))return;recovering=true;setConnected(false);const recovery=gate.current.ticket();try{const r=await snapshot(false,recovery);if(r&&terminal(r.status))close();}catch{if(gate.current.current(recovery)&&recovery.revision===gate.current.state.revision){if(es.readyState===EventSource.OPEN)setConnected(true);else{close();gate.current.touch();setConnecting(false);setAction(null);action.current=null;setError('연결이 끊어졌어요. 서버 실행 상태를 확인한 뒤 다시 검토해 주세요.');setRun(r=>r?{...r,status:'failed'}:r);}}}finally{recovering=false;}};
 },[close,snapshot]);
 const reset=useCallback(()=>{const old=gate.current.state.runId;gate.current.begin();close();action.current=null;resolveTokens.current.clear();setRun(null);setError('');setConnecting(false);setAction(null);setResolving([]);remoteCancel(old||undefined);},[close,remoteCancel]);
 const start=useCallback(async(body:StartRunRequest)=>{if(action.current)return false;const old=gate.current.state.runId;const ticket=gate.current.begin();close();remoteCancel(old||undefined);const token=Symbol();action.current=token;setAction('start');setConnecting(true);setError('');try{const result=await post<{runId:string}>('/api/runs',body);if(!gate.current.bind(ticket,result.runId)){remoteCancel(result.runId);return false;}setRun({id:result.runId,status:'running',stage:'analyzing',criteria:[],items:[],documents:[],events:[]});await snapshot();if(gate.current.state.runId===result.runId)connect(result.runId);return true;}catch(e){if(gate.current.state.generation===ticket.generation){setError((e as Error).message);setConnecting(false);}return false;}finally{if(action.current===token){action.current=null;setAction(null);setConnecting(false);}}},[close,remoteCancel,snapshot,connect]);
 const command=useCallback(async(name:string,body:unknown)=>{const id=gate.current.state.runId;if(!id||action.current)return false;const token=Symbol();action.current=token;setAction(name);setError('');const ticket=gate.current.touch();try{const result=await post<ReviewRun>(`/api/runs/${id}/${name}`,body);if(gate.current.snapshot(ticket,result,true))setRun(result);if(gate.current.current(ticket)&&!source.current)connect(id);return gate.current.current(ticket);}catch(e){if(gate.current.current(ticket))setError((e as Error).message);return false;}finally{if(action.current===token){action.current=null;setAction(null);}}},[connect]);
 const stop=useCallback(async()=>{const id=gate.current.state.runId;const ticket=gate.current.begin(id);close();action.current=null;resolveTokens.current.clear();setAction(null);setResolving([]);setConnecting(false);setRun(r=>r?{...r,status:'cancelled',stage:'idle' as any}:r);try{if(id)await post(`/api/runs/${id}/cancel`);return true;}catch(e){if(gate.current.current(ticket))setError((e as Error).message);return false;}},[close]);
 const resolve=useCallback(async(item:Item,status:'pass'|'fail'|'review',note:string)=>{if(!note.trim())return false;const id=gate.current.state.runId;if(!id)return false;const token=Symbol();resolveTokens.current.set(item.id,token);setResolving(x=>[...x,item.id]);const ticket=gate.current.touch();try{const result=await post<ResolveItemResponse>(`/api/runs/${id}/items/${item.id}/resolve`,{status,note});if(gate.current.current(ticket)&&resolveTokens.current.get(item.id)===token){gate.current.touch();setRun(r=>r?{...r,items:r.items.map(i=>i.id===result.item.id?result.item:i),summary:result.summary}:r);return true;}return false;}catch(e){if(gate.current.current(ticket))setError((e as Error).message);return false;}finally{if(resolveTokens.current.get(item.id)===token){resolveTokens.current.delete(item.id);setResolving(x=>x.filter(v=>v!==item.id));}}},[]);
 useEffect(()=>()=>{gate.current.begin();source.current?.close();},[]);
 return {run,error,setError,connecting,connected,pendingAction,resolving,pending:connecting||!!pendingAction||run?.status==='running',start,reset,stop,resolve,confirm:(body:ConfirmCriteriaRequest)=>command('criteria/confirm',body),revise:(body:unknown)=>command('criteria/revise',body),attach:(body:unknown)=>command('documents',body)};
}
