async page => {
  const config=await page.evaluate(()=>window.__REFERENCE_CAPTURE_CONFIG||{});
  const entry=config.entryUrl||page.url();
  const output=config.outputDirectory||'architecture/ui/reference';
  const origin=entry.match(/^https?:\/\/[^/]+/)[0];
  const referencePath=config.referencePath||'/architecture/ui/reference';
  const fontPath=config.fontPath||'/architecture/ui/fonts';
  const measurements=[];
  const serializeDom=()=>{
    const properties=['display','visibility','position','inset','top','right','bottom','left','z-index','box-sizing','width','height','min-width','max-width','min-height','max-height','margin','padding','gap','row-gap','column-gap','grid-template-columns','grid-template-rows','grid-auto-flow','flex-direction','flex-wrap','flex-grow','flex-shrink','flex-basis','align-items','align-content','align-self','justify-content','justify-items','justify-self','font-family','font-size','font-weight','font-style','font-synthesis','line-height','letter-spacing','text-align','text-transform','white-space','color','background-color','background-image','background-size','background-position','border','border-top','border-right','border-bottom','border-left','border-radius','box-shadow','text-shadow','opacity','transform','transform-origin','translate','rotate','scale','filter','backdrop-filter','clip-path','overflow','overflow-x','overflow-y','object-fit','object-position','fill','stroke','stroke-width','stroke-dasharray','stroke-dashoffset','animation-name','animation-duration','animation-delay','animation-timing-function','animation-iteration-count','animation-play-state','animation-fill-mode','transition-property','transition-duration','transition-delay','transition-timing-function'];
    const elements=[document.body,...document.body.querySelectorAll('*')].filter(el=>!['SCRIPT','STYLE','NOSCRIPT'].includes(el.tagName));
    const indices=new Map(elements.map((el,i)=>[el,i]));
    const styles=style=>Object.fromEntries(properties.map(property=>[property,style.getPropertyValue(property)]).filter(([,value])=>value!==''));
    const tree=elements.map((el,index)=>{
      const rect=el.getBoundingClientRect(),css=getComputedStyle(el);
      const attributes=Object.fromEntries([...el.attributes].filter(attr=>/^(id|class|role|type|name|title|alt|href|target|open|disabled|checked|tabindex|value|viewBox|d|x|y|x1|x2|y1|y2|cx|cy|r|rx|ry|width|height|points|fill|stroke|stroke-width|stroke-linecap|stroke-linejoin|transform)$/.test(attr.name)||/^(aria-|data-)/.test(attr.name)).map(attr=>[attr.name,attr.value]));
      const pseudo={};for(const key of ['::before','::after']){const value=getComputedStyle(el,key);if(value.content!=='none'&&value.content!=='normal')pseudo[key]={content:value.content,style:styles(value)};}
      return {index,parent:indices.get(el.parentElement)??null,tag:el.tagName.toLowerCase(),attributes,text:[...el.childNodes].filter(node=>node.nodeType===Node.TEXT_NODE).map(node=>node.textContent).join(''),...(['INPUT','TEXTAREA','SELECT'].includes(el.tagName)&&el.type!=='file'?{value:el.value}:{}),box:{x:rect.x,y:rect.y,width:rect.width,height:rect.height},scroll:{left:el.scrollLeft,top:el.scrollTop,width:el.scrollWidth,height:el.scrollHeight},style:styles(css),...(Object.keys(pseudo).length?{pseudo}:{})};
    });
    const portable=value=>JSON.parse(JSON.stringify(value,(_,entry)=>typeof entry==='number'&&!Number.isFinite(entry)?String(entry):entry));
    const animations=document.getAnimations().map(animation=>portable({target:indices.get(animation.effect?.target)??null,playState:animation.playState,currentTime:animation.currentTime,playbackRate:animation.playbackRate,timing:animation.effect?.getTiming(),computedTiming:animation.effect?.getComputedTiming(),keyframes:animation.effect?.getKeyframes()}));
    return {capturedAt:new Date().toISOString(),performanceTime:performance.now(),url:location.href,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scrollX,scrollY},motion:{app:document.documentElement.dataset.motion??null,appStored:location.protocol==='about:'?null:localStorage.getItem('trace-demo-motion'),osReduce:matchMedia('(prefers-reduced-motion: reduce)').matches,animationFreeze:'none'},eventSequence:window.__visual?.run()?.events.map(event=>({type:event.type,sequence:event.sequence,timestamp:event.timestamp}))||[],tree,animations};
  };
  page.setDefaultTimeout(12000);
  const fonts=await (await page.request.get(origin+fontPath+'/fonts.css')).text();
  const blockedExternal=[];
  await page.route('**/*',route=>{
    const url=route.request().url();
    if(url.startsWith('https://fonts.googleapis.com/'))return route.fulfill({contentType:'text/css',body:fonts.replaceAll('url(./','url('+origin+fontPath+'/')});
    if(url.startsWith(origin+'/')||/^(data|blob|about):/.test(url))return route.continue();
    blockedExternal.push(url.split('?')[0]);return route.abort('blockedbyclient');
  });
  await page.setViewportSize({width:1440,height:960});
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.evaluate(()=>localStorage.setItem('trace-demo-motion','on'));
  await page.goto(entry);
  await page.getByRole('button',{name:'검토 기준부터 시작하기',exact:true}).waitFor();
  await page.evaluate(()=>{
    window.__referenceDomSnapshots=[];
    window.__referenceEnvironment={userAgent:navigator.userAgent,platform:navigator.platform,language:navigator.language,languages:[...navigator.languages],timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,devicePixelRatio};
  });
  const shot=async(name,note='')=>{
    await page.evaluate(()=>document.fonts.ready);
    await page.waitForTimeout(650);
    const livePhase=/^(07|08|13|20)-/.test(name);
    let finiteAnimationsSettled=null;
    if(!livePhase){
      try{
        await page.waitForFunction(()=>document.getAnimations().every(animation=>animation.playState!=='running'||!Number.isFinite(animation.effect?.getComputedTiming().endTime)),{},{timeout:5000});
        await page.waitForFunction(()=>[...document.querySelectorAll('.workflow-input-card,.frr-focus-view,.ledger-shell,.dashboard-source-view')].every(element=>Number(getComputedStyle(element).opacity)>=.999),{},{timeout:5000});
        finiteAnimationsSettled=true;
      }catch{finiteAnimationsSettled=false;}
    }
    await page.screenshot({path:output+'/'+name+'.png'});
    const settling={livePhase,finiteAnimationsSettled,minimumSettleMs:650,animationFreeze:'none'};
    const dom={id:name,synthetic:true,settling,screenshotTiming:'DOM sampled immediately after viewport screenshot; live animations are not frozen.',main:await page.evaluate(serializeDom),frames:[]};
    for(const frame of page.frames().slice(1))dom.frames.push(await frame.evaluate(serializeDom));
    await page.evaluate(value=>window.__referenceDomSnapshots.push(value),dom);
    const result=await page.evaluate(()=>{
      const selectors=['.app-shell','.app-header','.workflow-steps','.workflow-main','main','.workflow-heading','.workflow-input-card','.workflow-analysis-stage','.workflow-stage-body','.criteria-confirmation','.criteria-source-pane','.live-review-workspace','.frr-workspace','.frr-source','.frr-detail','.frr-file','.dashboard-modal','.dashboard-preview-frame','.dashboard-builder','.dashboard-activity','.ledger-modal','.ledger-mapping-table','h1'];
      const boxes={};for(const selector of selectors){const el=document.querySelector(selector);if(el){const b=el.getBoundingClientRect(),s=getComputedStyle(el);boxes[selector]={x:b.x,y:b.y,width:b.width,height:b.height,fontFamily:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight,color:s.color,background:s.backgroundColor,borderRadius:s.borderRadius,padding:s.padding,gap:s.gap};}}
      return {viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},page:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,horizontalOverflow:document.documentElement.scrollWidth>innerWidth},motion:{app:document.documentElement.dataset.motion,osReduce:matchMedia('(prefers-reduced-motion: reduce)').matches},fonts:{status:document.fonts.status,dmSans:document.fonts.check('16px "DM Sans"'),notoSansKr:document.fonts.check('16px "Noto Sans KR"'),faces:[...document.fonts].map(f=>({family:f.family,status:f.status,weight:f.weight}))},boxes};
    });
    const frames=[];
    for(const frame of page.frames().slice(1)) frames.push(await frame.evaluate(()=>({url:location.href,title:document.title,theme:document.querySelector('#dashboard-root')?.getAttribute('data-theme'),distribution:document.querySelector('#dashboard-root')?.getAttribute('data-distribution'),canvasCount:document.querySelectorAll('canvas').length,visibleText:document.body?.innerText.slice(0,12000),reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,pageWidth:document.documentElement.scrollWidth,viewportWidth:innerWidth,fontFamily:getComputedStyle(document.body).fontFamily})));
    measurements.push({id:name,note,capturedAt:new Date().toISOString(),url:page.url(),mockOrigin:origin,synthetic:true,settling,visibleText:(await page.locator('body').innerText()).slice(0,24000),frames,...result});await page.evaluate(value=>window.__referenceMeasurements=value,measurements);
  };
  await page.waitForTimeout(800);
  await shot('01-landing-desktop','Built-in landing example, no uploaded data.');
  await page.setViewportSize({width:390,height:844});
  await shot('02-landing-mobile','390 × 844 responsive landing.');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('button',{name:'모션 ON',exact:true}).click();
  await shot('03-landing-mobile-motion-off','Both OS reduced motion and explicit app motion OFF.');
  await page.setViewportSize({width:1440,height:960});
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.getByRole('button',{name:'모션 OFF',exact:true}).click();
  await page.getByRole('button',{name:'검토 기준부터 시작하기',exact:true}).click();
  await page.locator('.workflow-input-card').waitFor();
  await shot('04-criteria-input-empty','File input mode before upload.');
  await page.getByRole('button',{name:'말로 기준 알려주기 원하는 조건을 직접 입력'}).click();
  await page.locator('#criteria-input').fill('압축강도는 28일 기준 25 MPa 이상이어야 합니다. 흡수율은 상온에서 5% 이하, 외관에는 균열이 없어야 합니다.');
  await shot('05-criteria-natural-language','Synthetic criteria text entered; no model called.');
  await page.getByRole('button',{name:'기준 파일 넣기 기준서·규정·표준 문서'}).click();
  await page.locator('input[type=file]').first().setInputFiles(output+'/synthetic-fixture.json');
  await page.getByRole('button',{name:/합성_품질기준.xlsx XLSX/}).waitFor();
  await shot('06-criteria-input-file','Mock upload response returns synthetic structured workbook preview.');
  await page.getByRole('button',{name:'기준 정리하기',exact:true}).click();
  await page.evaluate(()=>window.__visual.startReading());
  await page.locator('.workflow-analysis-stage').waitFor();
  await page.waitForTimeout(1100);
  await shot('07-criteria-reading','Synthetic activity snapshot: E2B read operation, not a real external execution.');
  await page.evaluate(()=>window.__visual.context());
  await page.waitForTimeout(700);
  await shot('08-criteria-context','Synthetic context activity; distinguishes reading from interpretation.');
  await page.evaluate(()=>window.__visual.confirmReady());
  await page.getByRole('button',{name:'기준 확정 · 검토 파일 넣기'}).waitFor({timeout:10000});
  await page.waitForTimeout(400);
  await shot('09-criteria-confirmation','Three synthetic criteria, editable HITL table and original source pane.');
  await page.getByRole('button',{name:'흡수율 수정 열기'}).click();
  await shot('10-criteria-hitl-editor','Inline editor opened for the synthetic absorption criterion.');
  await page.getByRole('button',{name:'흡수율 수정 닫기'}).click();
  await page.getByRole('button',{name:'기준 확정 · 검토 파일 넣기'}).click();
  await page.getByRole('button',{name:'이 기준으로 검토하기',exact:true}).waitFor();
  await shot('11-target-input-empty','Explicit criteria confirmation completed before target upload.');
  await page.locator('input[type=file]').first().setInputFiles(output+'/synthetic-fixture.json');
  await page.getByRole('button',{name:/합성_시험성적서_A.xlsx XLSX/}).waitFor();
  await shot('12-target-input-file','Synthetic target added.');
  await page.getByRole('button',{name:'이 기준으로 검토하기',exact:true}).click();
  await page.evaluate(()=>window.__visual.reviewActive());
  await page.locator('.live-review-workspace').waitFor();
  await page.waitForTimeout(1200);
  await shot('13-review-active','Synthetic received events: one pass, one fail and one review branch.');
  await page.evaluate(()=>window.__visual.complete());
  await page.getByRole('heading',{name:'파일별로, 결과와 근거를 함께.'}).waitFor({timeout:10000});
  await page.locator('.frr-file').first().waitFor();
  await page.waitForTimeout(700);
  await shot('14-results','Completed synthetic review: counts 1/1/1.');
  await page.locator('.frr-item').filter({hasText:'흡수율'}).click();
  await page.getByRole('tabpanel',{name:'선택한 항목 상세'}).waitFor();
  await shot('15-result-detail-fail','Synthetic failed absorption item selected; target row and decision explanation.');
  await page.getByRole('button',{name:'항목 목록',exact:true}).click();
  await page.locator('.frr-item').filter({hasText:'외관'}).click();
  await shot('16-result-detail-review','Unreadable synthetic appearance result, human review controls displayed; no resolution submitted.');
  await page.getByRole('tab',{name:/적용 기준/}).click();
  await shot('17-result-applied-criteria','Applied criteria with their original source references.');
  await page.locator('.frr-criterion').filter({hasText:'흡수율'}).getByRole('button').click();
  await page.getByText('연결된 기준 원문',{exact:true}).waitFor();
  await shot('18-result-criterion-source','Criterion source replaces target preview, focused on the synthetic source row.');
  await page.getByRole('button',{name:'나만의 대시보드',exact:true}).click();
  await page.locator('#dashboard-instruction').waitFor();
  await shot('19-dashboard-controls','Actual DashboardModal customization inputs before generation.');
  await page.getByRole('button',{name:'대시보드 만들기',exact:true}).click();
  await page.getByRole('button',{name:'생성 취소',exact:true}).waitFor();
  await shot('20-dashboard-generating','Synthetic generating job; no model, E2B or build was invoked by this UI action.');
  await page.evaluate(()=>window.__visual.dashboardReady());
  await page.locator('.dashboard-preview-frame').waitFor({timeout:20000});
  const frame=page.frameLocator('.dashboard-preview-frame');
  await frame.locator('#dashboard-root[data-theme="light"]').waitFor();
  await frame.locator('canvas').waitFor();
  await page.waitForTimeout(500);
  await shot('21-dashboard-light','Self-contained deterministic GSPEC designer HTML in actual sandboxed host modal; synthetic data.');
  await page.getByRole('button',{name:'구성 수정',exact:true}).click();
  await page.getByRole('button',{name:'다크 · 차트 중심',exact:true}).click();
  await shot('22-dashboard-customize','Dark/bar-chart suggestion selected while current light preview remains visible.');
  await page.getByRole('button',{name:'다시 구성',exact:true}).click();
  await page.getByRole('button',{name:'생성 취소',exact:true}).waitFor();
  await page.evaluate(()=>window.__visual.dashboardReady());
  await page.locator('.dashboard-preview-frame').waitFor({timeout:20000});
  await frame.locator('#dashboard-root[data-theme="dark"][data-distribution="bar"]').waitFor();
  await frame.locator('canvas').waitFor();
  await page.waitForTimeout(500);
  await shot('23-dashboard-dark','Synthetic deterministic dark theme and bar chart delivered through the real regeneration controls.');
  await page.locator('.dashboard-activity-toggle').click();
  await page.locator('.dashboard-terminal').waitFor();
  await shot('24-dashboard-activity','Actual activity disclosure showing explicitly synthetic local fixture log.');
  await page.getByRole('button',{name:'원본과 판정',exact:true}).click();
  await page.locator('.dashboard-source-view').waitFor();
  await page.waitForTimeout(400);
  await shot('25-dashboard-source','Host-owned source/evidence view with frozen synthetic review snapshot.');
  await page.getByRole('button',{name:'대시보드 닫기',exact:true}).click();
  await page.getByRole('button',{name:'내보내기',exact:true}).click();
  await page.getByRole('button',{name:'검토대장에 기록',exact:true}).click();
  await page.locator('.ledger-modal').waitFor();
  await shot('26-ledger-empty','Ledger modal before upload; no workbook has been written.');
  await page.getByLabel('XLSX 검토대장 선택').evaluate(input=>{
    const transfer=new DataTransfer();
    transfer.items.add(new File(['Synthetic upload token: local mock supplies parsed response; not a real workbook.'],'합성_검토대장.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));
    input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));
  });
  await page.getByRole('button',{name:'기입 위치 확인하기',exact:true}).click();
  await page.locator('.ledger-mapping-table').waitFor();
  await page.locator('#ledger-note').fill('합성 캡처용 메모: 원본 사진 확인 예정.');
  await shot('27-ledger-mapping','Synthetic mapping/proposal and optional human note; download is not executed and workbook processing is not asserted.');
  await page.getByRole('button',{name:'검토대장 창 닫기',exact:true}).click();
  await page.getByRole('button',{name:'검토 대상으로',exact:true}).click();
  await page.getByRole('tab',{name:/검토 항목/}).click();
  await page.setViewportSize({width:390,height:844});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('button',{name:'모션 ON',exact:true}).click();
  await page.evaluate(()=>window.scrollTo(0,0));
  await shot('28-results-mobile-motion-off','390 × 844 responsive results; OS reduced motion and app motion OFF; viewport crop, not full page.');
  await page.evaluate(value=>window.__referenceMeasurements=value,measurements);
  await page.evaluate(value=>window.__referenceBlockedExternal=value,blockedExternal);
  return {captured:measurements.length,url:page.url(),blockedExternal,buttons:await page.getByRole('button').allTextContents()};
}

