// Pure saved-evidence classifier. No network, browser, provider or filesystem operations.
import {calibrationAdmissionProblems} from './calibration.mjs';
export const SDK_SOURCE_SHA256='83f8c03ae28d3979b57f005ef530321fe064a279cf446b526bd28e61f707540f';
const SDK_REFS=[{"path":"C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json","sha256":"ca170ec143a88ed3043ac953eb3b2377b2b97304104f4e1e23316684ce2c35af","bytes":1416},{"path":"C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs","sha256":"a0f5715ea22354f922791a9c53dc012d5d5c067ff9cc4cd35ffb7cd272071a9f","bytes":704},{"path":"C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.js","sha256":"4e98f65f0a9d9bcab8cffc0c5cfdd87fd3f5b0be74fc494ff166a466b204cd44","bytes":648},{"path":"C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/package.json","sha256":"07c47543631fef9508760365dee9fbe958c562093ec8d122543949ed231f233f","bytes":876},{"path":"C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs","sha256":"3d36e2132d3c8b62397d23f0bb4177336aaee503203ae2a2c90fbeb5bf3317dd","bytes":1063},{"path":"C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.js","sha256":"a58fb2cec4293e7dcf73c58a179898a4f3986666451a19da4e731fa3af63265b","bytes":697},{"path":"C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/lib/coreBundle.js","sha256":"9393fa79e1c67c74edc26b610d65a4f7ed73d345a762465cc88340a33a2454ac","bytes":3425603}];
const ORIGIN='http://127.0.0.1:5210',identityKind='pinned-native-eventsource-request-identity';
const eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),one=a=>a.length===1?a[0]:null;
const headers=h=>{const entries=Object.entries(h??{}).map(([k,v])=>[k.toLowerCase(),String(v)]);return new Set(entries.map(x=>x[0])).size===entries.length?Object.fromEntries(entries):{};};
const frames=s=>s?[...(s.callFrames??[]),...frames(s.parent)]:[];
const sourceFor=url=>{try{return new URL(url).pathname==='/api/activity/events'?'useActivityObserver.ts':'useReview.ts';}catch{return null;}};
const sourceStack=(stack,file)=>typeof stack==='string'&&typeof file==='string'&&new RegExp('http://127\\.0\\.0\\.1:5210/src/'+file.replace('.','\\.')+'(?:\\?[^\\s)]*)?:\\d+:\\d+').test(stack);
function scoped(url,runIds){try{const u=new URL(url);if(u.origin!==ORIGIN||u.hash)return false;if(u.pathname==='/api/activity/events')return u.search==='';return runIds.some(id=>u.pathname==='/api/runs/'+id+'/events')&&/^\?after=\d+$/.test(u.search);}catch{return false;}}
function identityOkay(i,p,frame){return i?.kind===identityKind&&i.sourceGuardRequired===true&&i.nativeFrameId===frame&&i.url===p.url&&i.method==='GET'&&i.resourceType==='eventsource'&&typeof i.publicGuid==='string'&&!!i.publicGuid&&typeof i.nativeRequestId==='string'&&!!i.nativeRequestId&&Number.isFinite(i.nativeTimestamp)&&Number.isFinite(i.nativeWallTime)&&['sameClientConnection','exactDispatcherObject','exactMappedMainFrame','uniqueOwnNativeSymbol','reciprocalServerRequest','reciprocalRedirects'].every(k=>i.proof?.[k]===true);}
function sameCore(a,b){return ['kind','publicGuid','nativeRequestId','nativeTimestamp','nativeWallTime','nativeFrameId','url','method','resourceType'].every(k=>a?.[k]===b?.[k]);}
export function classifyNativeEventSourceCloses(saved,{documentUrl=ORIGIN+'/'}={}){
 const raw=saved.nativeEventSource??{},observer=raw.observer??{},rows=observer.rows??[],network=saved.network??[],failures=saved.networkFailures??[],events=raw.cdp??[],scope=raw.scope??{};
 const globalProblems=[];const need=(ok,message)=>{if(!ok)globalProblems.push(message);};
 need(typeof documentUrl==='string'&&(()=>{try{return new URL(documentUrl).origin===ORIGIN&&new URL(documentUrl).href===documentUrl&&!new URL(documentUrl).hash;}catch{return false;}})()&&scope.documentUrl===documentUrl,'Exact immutable-plan document URL not supplied/matched');
 need(scope.origin===ORIGIN&&Array.isArray(scope.runIds)&&scope.runIds.every(id=>typeof id==='string'&&/^[A-Za-z0-9_-]+$/.test(id))&&new Set(scope.runIds).size===scope.runIds.length,'Missing exact original endpoint scope');
 const runIds=scope.runIds??[];
 need(raw.sdkBinding?.kind==='verified-native-eventsource-sdk-binding'&&raw.sdkBinding.version==='1.62.1'&&raw.sdkBinding.sourceSha256===SDK_SOURCE_SHA256&&eq(raw.sdkBinding.refs,SDK_REFS),'Missing exact verified pinned SDK source');
 need(observer.schemaVersion===1&&observer.wrapperIntegrity===true&&observer.prototypeIdentity===true&&observer.restored===false,'Missing intact passive EventSource observation');
 need(Array.isArray(observer.observerErrors)&&observer.observerErrors.length===0&&Array.isArray(raw.errors)&&raw.errors.length===0,'Observer/network capture errors');
 need(typeof raw.frameId==='string'&&!!raw.frameId&&raw.finalSnapshotCaptured===true&&raw.captureClosed===true&&typeof saved.contextClosedAt==='string','Capture not complete and closed');
 globalProblems.push(...calibrationAdmissionProblems(raw,{documentUrl}));
 need(rows.every((r,i)=>r.sequence===i+1&&Number.isFinite(r.monotonicMs)&&Number.isFinite(r.timeOrigin)&&(i===0||r.monotonicMs>=rows[i-1].monotonicMs)),'Missing/unordered native observation sequence');
 need(new Set(network.map(p=>p.id)).size===network.length,'Duplicate public Request IDs');
 const streamMembers=network.filter(p=>p.resourceType==='eventsource');
 need(streamMembers.every(p=>identityOkay(p.nativeIdentity,p,raw.frameId)&&identityOkay(p.nativeIdentityAtCapture,p,raw.frameId))&&new Set(streamMembers.map(p=>p.nativeIdentity.publicGuid)).size===streamMembers.length&&new Set(streamMembers.map(p=>p.nativeIdentityAtCapture.publicGuid)).size===streamMembers.length,'Missing or duplicate retained stream Request GUID identity');
 const c=raw.clockCalibration,r=c?.renderer?.result?.value;
 const before=c?.before?.metrics?.find(x=>x.name==='Timestamp')?.value*1000,after=c?.after?.metrics?.find(x=>x.name==='Timestamp')?.value*1000;
 const interval=row=>({lo:before+row.monotonicMs-r.monotonicMs,hi:after+row.monotonicMs-r.monotonicMs});
 need(rows.every(row=>row.timeOrigin===r?.timeOrigin)&&observer.snapshotAt?.timeOrigin===r?.timeOrigin&&Number.isFinite(observer.snapshotAt?.monotonicMs)&&observer.snapshotAt.monotonicMs>=(rows.at(-1)?.monotonicMs??0)&&new Date(observer.snapshotAt?.at).getTime()<new Date(saved.contextClosedAt).getTime(),'Observation crossed renderer time origin or final snapshot/context close ordering');
 const calls=rows.filter(x=>x.kind==='construct-call'),objects=rows.filter(x=>x.kind==='construct-return'&&scoped(x.url,runIds));
 need(new Set(objects.map(x=>x.objectId)).size===objects.length,'Repeated EventSource object identity');
 const starts=events.filter(e=>e.method==='Network.requestWillBeSent').map(e=>e.params);
 const originals=starts.filter(s=>!s.redirectResponse&&scoped(s.request?.url,runIds)&&s.request?.method==='GET'&&s.type==='EventSource');
 // All observed same-URL constructors participate, including unknown source callers.
 const candidates=object=>{const call=one(calls.filter(x=>x.callId===object.callId)),open=one(rows.filter(x=>x.kind==='native-open'&&x.objectId===object.objectId));if(!call||!open||!r)return [];
  const a=interval(call),b=interval(open);return originals.filter(s=>s.request.url===object.url&&s.frameId===raw.frameId&&s.timestamp*1000>=a.lo&&s.timestamp*1000<=b.hi);};
 const graph=new Map(objects.map(o=>[o.objectId,candidates(o)]));
 const scopedFailures=failures.filter(f=>network.find(p=>p.id===f.requestId)?.resourceType==='eventsource');
 const qualifiedNativeIds=new Set(),results=failures.map(failure=>{const errors=[];const require=(ok,message)=>{if(!ok)errors.push(message);};let join=null;
  const p=one(network.filter(p=>p.id===failure.requestId));
  if(!p||p.resourceType!=='eventsource')return {failure,classification:'OUTSIDE_EVENTSOURCE_SCOPE',reason:'Retained for the owning non-stream classifier',join:null};
  require(globalProblems.length===0,'Global capture integrity failed');
  require(failure.url===p.url&&failure.method==='GET'&&failure.failure?.errorText==='net::ERR_ABORTED'&&p.failedAt&&!p.finishedAt,'Not exact public canceled terminal');
  const final=p.nativeIdentityAtCapture,failed=p.nativeIdentityAtFailure,initial=p.nativeIdentity;
  require(identityOkay(initial,p,raw.frameId)&&identityOkay(failed,p,raw.frameId)&&identityOkay(final,p,raw.frameId)&&sameCore(initial,final)&&sameCore(failed,final),'Missing exact reciprocal Request identity at creation/failure/final capture');
  const nativeId=final?.nativeRequestId;
  const chainStarts=starts.filter(s=>s.requestId===nativeId),nativeFailures=events.filter(e=>e.method==='Network.loadingFailed'&&e.params.requestId===nativeId).map(e=>e.params),nativeFinished=events.filter(e=>e.method==='Network.loadingFinished'&&e.params.requestId===nativeId);
  const nativeFailure=one(nativeFailures),first=chainStarts[0],last=chainStarts.at(-1);
  require(chainStarts.length>=1&&chainStarts.length<=2&&chainStarts.every(s=>Number.isFinite(s.wallTime))&&!first?.redirectResponse&&scoped(first?.request?.url,runIds),'Unexpected/reconnected native request chain');
  require(nativeFailure?.canceled===true&&nativeFailure.errorText==='net::ERR_ABORTED'&&nativeFailure.type==='EventSource'&&nativeFinished.length===0,'Missing exact native canceled terminal');
  require(last?.request?.url===p.url&&last?.request?.method==='GET'&&last?.type==='EventSource'&&last?.frameId===raw.frameId&&last?.timestamp===final?.nativeTimestamp,'Failure Request is not exact native final hop');
  const originalPublic=one(network.filter(q=>q.nativeIdentity?.nativeRequestId===nativeId&&q.nativeIdentity?.nativeTimestamp===first?.timestamp&&q.url===first?.request?.url));
  require(chainStarts.every(s=>network.filter(q=>q.nativeIdentity?.nativeRequestId===s.requestId&&q.nativeIdentity?.nativeTimestamp===s.timestamp&&q.nativeIdentity?.nativeFrameId===s.frameId&&q.url===s.request?.url&&q.method===s.request?.method&&q.resourceType==='eventsource').length===1),'Native hop does not have exactly one retained public Request member');
  const eligible=objects.filter(o=>graph.get(o.objectId)?.includes(first));const object=one(eligible);
  require(!!object&&graph.get(object?.objectId)?.length===1,'Object/request association is missing or ambiguous');
  const objRows=rows.filter(x=>x.objectId===object?.objectId),construct=one(calls.filter(x=>x.callId===object?.callId)),open=one(objRows.filter(x=>x.kind==='native-open')),close=one(objRows.filter(x=>x.kind==='close-call')),closed=one(objRows.filter(x=>x.kind==='close-return'));
  require(!!construct&&object?.nativePrototype===true&&sourceStack(construct?.stack,sourceFor(first?.request?.url??ORIGIN)),'Constructor is not actual source-owned native EventSource');
  require(open?.isTrusted===true&&open.readyState===1&&!objRows.some(x=>x.kind==='native-error'),'No single trusted opened connection or error/reconnect observed');
  require(close?.readyState===1&&closed?.readyState===2&&closed?.returnedUndefined===true&&closed?.callId===close?.callId&&closed?.sequence>close?.sequence&&!objRows.some(x=>x.kind==='close-throw')&&sourceStack(close?.stack,sourceFor(first?.request?.url??ORIGIN)),'Missing original source-owned native OPEN→CLOSED call/return');
  require(construct?.sequence<object?.sequence&&object?.sequence<open?.sequence&&open?.sequence<close?.sequence,'Native object lifecycle order is invalid');
  if(close&&r&&nativeFailure){require(Number.isFinite(observer.snapshotAt?.monotonicMs)&&nativeFailure.timestamp*1000<=interval(observer.snapshotAt).lo,'Cancellation not observed definitively before final renderer snapshot/context close');require(nativeFailure.timestamp*1000>=interval(close).hi,'Cancellation was not definitively after original close under measured clock bracket');
   require(new Date(close.at).getTime()<new Date(saved.contextClosedAt).getTime(),'Context termination could own the cancellation');}
  if(object&&construct&&close&&r){const overlaps=objects.filter(o=>o!==object&&o.url===object.url).filter(o=>{const otherCall=one(calls.filter(x=>x.callId===o.callId)),otherClose=one(rows.filter(x=>x.objectId===o.objectId&&x.kind==='close-call'));return !otherCall||interval(otherCall).lo<=interval(close).hi&&(!otherClose||interval(otherClose).hi>=interval(construct).lo);});require(overlaps.length===0,'Same-URL object lifetimes overlap or are ambiguous');}
  const response=one(events.filter(e=>e.method==='Network.responseReceived'&&e.params.requestId===nativeId).map(e=>e.params));
  require(response?.type==='EventSource'&&response?.frameId===raw.frameId&&response?.response?.url===p.url&&response?.response?.status===200&&headers(response?.response?.headers)['content-type']?.split(';')[0].trim()==='text/event-stream'&&p.status===200&&headers(p.responseHeaders)['content-type']?.split(';')[0].trim()==='text/event-stream','Not an actual200 EventSource stream (204 is distinct)');
  if(response&&open&&close&&r)require(response.timestamp>=last?.timestamp&&response.timestamp*1000<=interval(open).hi&&response.timestamp*1000<interval(close).lo,'Response/open/close chronology is inconsistent');
  require(originalPublic&&identityOkay(originalPublic.nativeIdentity,originalPublic,raw.frameId)&&identityOkay(originalPublic.nativeIdentityAtCapture,originalPublic,raw.frameId)&&sameCore(originalPublic.nativeIdentity,originalPublic.nativeIdentityAtCapture)&&originalPublic.isMainFrame===true&&p.isMainFrame===true,'Original public Request identity is missing');
  const initiator=first?.initiator;require(initiator?.type==='script'&&frames(initiator.stack).some(f=>{try{return new URL(f.url).origin===ORIGIN&&new URL(f.url).pathname==='/src/'+sourceFor(first.request.url);}catch{return false;}}),'Original native initiation is outside actual source');
  if(chainStarts.length===1){require(originalPublic===p&&final?.redirectedFromGuid===null&&final?.redirectedToGuid===null&&p.redirectedFromId===null&&p.redirectedToId===null,'Unexpected direct-stream redirect link');}
  if(chainStarts.length===2){const prior=originalPublic,priorFinal=prior?.nativeIdentityAtCapture,redirect=last?.redirectResponse,declared=one((raw.redirects??[]).filter(d=>d.originalRequestId===prior?.id&&d.finalUrl===p.url));
   require(prior?.redirectedFromId===null&&prior?.redirectedToId===p.id&&p.redirectedFromId===prior?.id&&p.redirectedToId===null&&priorFinal?.redirectedToGuid===final?.publicGuid&&final?.redirectedFromGuid===priorFinal?.publicGuid&&priorFinal?.redirectedFromGuid===null&&final?.redirectedToGuid===null,'Redirect lacks exact reciprocal public/native links');
   require(redirect?.status===307&&redirect?.url===prior?.url&&headers(redirect?.headers).location===p.url&&prior?.status===307&&headers(prior?.responseHeaders).location===p.url&&declared?.status===307&&declared?.originalUrl===prior?.url,'Undeclared or mismatched307 redirect');
   const producer=saved.producer,producerRequest=one((producer?.requests??[]).filter(x=>String(x.id)===headers(response?.response?.headers)['x-g13-producer-request-id']));
   let parsed;try{parsed=new URL(p.url);}catch{}
   require(parsed?.origin===producer?.address?.origin&&/^http:\/\/127\.0\.0\.1:\d+$/.test(producer?.address?.origin??'')&&parsed?.pathname===new URL(prior?.url??ORIGIN).pathname&&parsed?.search==='?g13RequestId=request-'+prior?.id,'Redirect destination is not the observed local producer request');
   const browserId='request-'+prior?.id;
   require(producerRequest?.browserRequestId===browserId&&headers(response?.response?.headers)['x-g13-request-id']===browserId&&headers(p.responseHeaders)['x-g13-request-id']===browserId&&headers(p.responseHeaders)['x-g13-producer-request-id']===String(producerRequest?.id)&&producerRequest?.path===parsed?.pathname&&producerRequest?.query===parsed?.search&&producerRequest?.status===200&&headers(producerRequest?.responseHeaders)['x-g13-request-id']===browserId&&headers(producerRequest?.responseHeaders)['x-g13-producer-request-id']===String(producerRequest?.id)&&headers(producerRequest?.responseHeaders)['content-type']?.split(';')[0].trim()==='text/event-stream','Producer/browser stream identity mismatch');
   require((producer?.events??[]).filter(x=>['stream-open','run-stream-open'].includes(x.kind)&&x.id===producerRequest?.id).length===1&&producerRequest?.closedAt&&producerRequest?.finished===false&&!producerRequest?.responseError&&(producer?.errors??[]).length===0,'Producer stream was not uniquely opened and remotely canceled');
   require(!(producer?.events??[]).some(x=>x.kind==='stream-end-input'&&[...(x.streamIds??[]),...(x.runStreamIds??[])].includes(producerRequest?.id)),'Producer EOF initiated termination');
   const producerCleanup=one((producer?.events??[]).filter(x=>x.kind==='producer-cleanup-start'));require(producerCleanup&&new Date(producerRequest?.closedAt).getTime()<new Date(producerCleanup.at).getTime()&&new Date(producerRequest?.closedAt).getTime()>=new Date(close?.at).getTime(),'Producer cleanup or an earlier remote close could own termination');
  }
  require(scopedFailures.filter(f=>f.requestId===p.id).length===1,'Duplicate public failure terminal');
  if(errors.length===0){qualifiedNativeIds.add(nativeId);join={kind:'unique-closed-native-eventsource-lifecycle',objectId:object.objectId,constructCallId:construct.callId,closeCallId:close.callId,originalPublicRequestId:originalPublic.id,finalPublicRequestId:p.id,nativeRequestId:nativeId,hopCount:chainStarts.length,originalUrl:object.url,finalUrl:p.url};}
  return {failure,classification:errors.length?'ERROR':'QUALIFIED_NATIVE_EVENTSOURCE_CLOSE',reason:errors.length?errors.join('; '):'Unique source-owned opened native object close joined to exact native cancellation',join};
 });
 const scopedIds=new Set(originals.map(s=>s.requestId));
 const unjoinedNativeFailures=events.filter(e=>e.method==='Network.loadingFailed'&&scopedIds.has(e.params.requestId)&&!qualifiedNativeIds.has(e.params.requestId));
 const protocol204=events.filter(e=>e.method==='Network.responseReceived'&&scopedIds.has(e.params.requestId)&&e.params.response?.status===204).map(e=>({nativeRequestId:e.params.requestId,url:e.params.response.url,status:204,classification:'HTTP_204_TERMINATION_ONLY',expectedClose:false}));
 return {globalProblems,results,rawFailureCount:failures.length,qualifiedCount:results.filter(x=>x.classification==='QUALIFIED_NATIVE_EVENTSOURCE_CLOSE').length,unexpectedStreamFailureCount:results.filter(x=>x.classification==='ERROR').length,unjoinedNativeFailures,protocol204,rawFailuresPreserved:true,okay:globalProblems.length===0&&!results.some(x=>x.classification==='ERROR')&&unjoinedNativeFailures.length===0};
}
